/*****************************************************************************
 *   Copyright(C)2009-2022 by VSF Team                                       *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 ****************************************************************************/

/*****************************************************************************
 *   Copyright(C)2009-2020 by GorgonMeducer<embedded_zhuoran@hotmail.com>    *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 ****************************************************************************/

#ifndef __VSF_MREPEAT_H__
#define __VSF_MREPEAT_H__

#include "./vsf_connect_macro.h"


#ifdef __cplusplus
extern "C" {
#endif

#define VSF_MREPEAT_LIMIT                       256

#if (!defined(__STDC_VERSION__) || __STDC_VERSION__ < 199901L)

#define VSF_MREPEAT(__COUNT, __MACRO, __PARAM)  VSF_MCONNECT(VSF_MREPEAT, __COUNT)(__MACRO, __PARAM)

#define VSF_MREPEAT0(  __MACRO, __PARAM)
#define VSF_MREPEAT1(  __MACRO, __PARAM)        VSF_MREPEAT0(  __MACRO, __PARAM)   __MACRO(  0, __PARAM)
#define VSF_MREPEAT2(  __MACRO, __PARAM)        VSF_MREPEAT1(  __MACRO, __PARAM)   __MACRO(  1, __PARAM)
#define VSF_MREPEAT3(  __MACRO, __PARAM)        VSF_MREPEAT2(  __MACRO, __PARAM)   __MACRO(  2, __PARAM)
#define VSF_MREPEAT4(  __MACRO, __PARAM)        VSF_MREPEAT3(  __MACRO, __PARAM)   __MACRO(  3, __PARAM)
#define VSF_MREPEAT5(  __MACRO, __PARAM)        VSF_MREPEAT4(  __MACRO, __PARAM)   __MACRO(  4, __PARAM)
#define VSF_MREPEAT6(  __MACRO, __PARAM)        VSF_MREPEAT5(  __MACRO, __PARAM)   __MACRO(  5, __PARAM)
#define VSF_MREPEAT7(  __MACRO, __PARAM)        VSF_MREPEAT6(  __MACRO, __PARAM)   __MACRO(  6, __PARAM)
#define VSF_MREPEAT8(  __MACRO, __PARAM)        VSF_MREPEAT7(  __MACRO, __PARAM)   __MACRO(  7, __PARAM)
#define VSF_MREPEAT9(  __MACRO, __PARAM)        VSF_MREPEAT8(  __MACRO, __PARAM)   __MACRO(  8, __PARAM)
#define VSF_MREPEAT10( __MACRO, __PARAM)        VSF_MREPEAT9(  __MACRO, __PARAM)   __MACRO(  9, __PARAM)
#define VSF_MREPEAT11( __MACRO, __PARAM)        VSF_MREPEAT10( __MACRO, __PARAM)   __MACRO( 10, __PARAM)
#define VSF_MREPEAT12( __MACRO, __PARAM)        VSF_MREPEAT11( __MACRO, __PARAM)   __MACRO( 11, __PARAM)
#define VSF_MREPEAT13( __MACRO, __PARAM)        VSF_MREPEAT12( __MACRO, __PARAM)   __MACRO( 12, __PARAM)
#define VSF_MREPEAT14( __MACRO, __PARAM)        VSF_MREPEAT13( __MACRO, __PARAM)   __MACRO( 13, __PARAM)
#define VSF_MREPEAT15( __MACRO, __PARAM)        VSF_MREPEAT14( __MACRO, __PARAM)   __MACRO( 14, __PARAM)
#define VSF_MREPEAT16( __MACRO, __PARAM)        VSF_MREPEAT15( __MACRO, __PARAM)   __MACRO( 15, __PARAM)
#define VSF_MREPEAT17( __MACRO, __PARAM)        VSF_MREPEAT16( __MACRO, __PARAM)   __MACRO( 16, __PARAM)
#define VSF_MREPEAT18( __MACRO, __PARAM)        VSF_MREPEAT17( __MACRO, __PARAM)   __MACRO( 17, __PARAM)
#define VSF_MREPEAT19( __MACRO, __PARAM)        VSF_MREPEAT18( __MACRO, __PARAM)   __MACRO( 18, __PARAM)
#define VSF_MREPEAT20( __MACRO, __PARAM)        VSF_MREPEAT19( __MACRO, __PARAM)   __MACRO( 19, __PARAM)
#define VSF_MREPEAT21( __MACRO, __PARAM)        VSF_MREPEAT20( __MACRO, __PARAM)   __MACRO( 20, __PARAM)
#define VSF_MREPEAT22( __MACRO, __PARAM)        VSF_MREPEAT21( __MACRO, __PARAM)   __MACRO( 21, __PARAM)
#define VSF_MREPEAT23( __MACRO, __PARAM)        VSF_MREPEAT22( __MACRO, __PARAM)   __MACRO( 22, __PARAM)
#define VSF_MREPEAT24( __MACRO, __PARAM)        VSF_MREPEAT23( __MACRO, __PARAM)   __MACRO( 23, __PARAM)
#define VSF_MREPEAT25( __MACRO, __PARAM)        VSF_MREPEAT24( __MACRO, __PARAM)   __MACRO( 24, __PARAM)
#define VSF_MREPEAT26( __MACRO, __PARAM)        VSF_MREPEAT25( __MACRO, __PARAM)   __MACRO( 25, __PARAM)
#define VSF_MREPEAT27( __MACRO, __PARAM)        VSF_MREPEAT26( __MACRO, __PARAM)   __MACRO( 26, __PARAM)
#define VSF_MREPEAT28( __MACRO, __PARAM)        VSF_MREPEAT27( __MACRO, __PARAM)   __MACRO( 27, __PARAM)
#define VSF_MREPEAT29( __MACRO, __PARAM)        VSF_MREPEAT28( __MACRO, __PARAM)   __MACRO( 28, __PARAM)
#define VSF_MREPEAT30( __MACRO, __PARAM)        VSF_MREPEAT29( __MACRO, __PARAM)   __MACRO( 29, __PARAM)
#define VSF_MREPEAT31( __MACRO, __PARAM)        VSF_MREPEAT30( __MACRO, __PARAM)   __MACRO( 30, __PARAM)
#define VSF_MREPEAT32( __MACRO, __PARAM)        VSF_MREPEAT31( __MACRO, __PARAM)   __MACRO( 31, __PARAM)
#define VSF_MREPEAT33( __MACRO, __PARAM)        VSF_MREPEAT32( __MACRO, __PARAM)   __MACRO( 32, __PARAM)
#define VSF_MREPEAT34( __MACRO, __PARAM)        VSF_MREPEAT33( __MACRO, __PARAM)   __MACRO( 33, __PARAM)
#define VSF_MREPEAT35( __MACRO, __PARAM)        VSF_MREPEAT34( __MACRO, __PARAM)   __MACRO( 34, __PARAM)
#define VSF_MREPEAT36( __MACRO, __PARAM)        VSF_MREPEAT35( __MACRO, __PARAM)   __MACRO( 35, __PARAM)
#define VSF_MREPEAT37( __MACRO, __PARAM)        VSF_MREPEAT36( __MACRO, __PARAM)   __MACRO( 36, __PARAM)
#define VSF_MREPEAT38( __MACRO, __PARAM)        VSF_MREPEAT37( __MACRO, __PARAM)   __MACRO( 37, __PARAM)
#define VSF_MREPEAT39( __MACRO, __PARAM)        VSF_MREPEAT38( __MACRO, __PARAM)   __MACRO( 38, __PARAM)
#define VSF_MREPEAT40( __MACRO, __PARAM)        VSF_MREPEAT39( __MACRO, __PARAM)   __MACRO( 39, __PARAM)
#define VSF_MREPEAT41( __MACRO, __PARAM)        VSF_MREPEAT40( __MACRO, __PARAM)   __MACRO( 40, __PARAM)
#define VSF_MREPEAT42( __MACRO, __PARAM)        VSF_MREPEAT41( __MACRO, __PARAM)   __MACRO( 41, __PARAM)
#define VSF_MREPEAT43( __MACRO, __PARAM)        VSF_MREPEAT42( __MACRO, __PARAM)   __MACRO( 42, __PARAM)
#define VSF_MREPEAT44( __MACRO, __PARAM)        VSF_MREPEAT43( __MACRO, __PARAM)   __MACRO( 43, __PARAM)
#define VSF_MREPEAT45( __MACRO, __PARAM)        VSF_MREPEAT44( __MACRO, __PARAM)   __MACRO( 44, __PARAM)
#define VSF_MREPEAT46( __MACRO, __PARAM)        VSF_MREPEAT45( __MACRO, __PARAM)   __MACRO( 45, __PARAM)
#define VSF_MREPEAT47( __MACRO, __PARAM)        VSF_MREPEAT46( __MACRO, __PARAM)   __MACRO( 46, __PARAM)
#define VSF_MREPEAT48( __MACRO, __PARAM)        VSF_MREPEAT47( __MACRO, __PARAM)   __MACRO( 47, __PARAM)
#define VSF_MREPEAT49( __MACRO, __PARAM)        VSF_MREPEAT48( __MACRO, __PARAM)   __MACRO( 48, __PARAM)
#define VSF_MREPEAT50( __MACRO, __PARAM)        VSF_MREPEAT49( __MACRO, __PARAM)   __MACRO( 49, __PARAM)
#define VSF_MREPEAT51( __MACRO, __PARAM)        VSF_MREPEAT50( __MACRO, __PARAM)   __MACRO( 50, __PARAM)
#define VSF_MREPEAT52( __MACRO, __PARAM)        VSF_MREPEAT51( __MACRO, __PARAM)   __MACRO( 51, __PARAM)
#define VSF_MREPEAT53( __MACRO, __PARAM)        VSF_MREPEAT52( __MACRO, __PARAM)   __MACRO( 52, __PARAM)
#define VSF_MREPEAT54( __MACRO, __PARAM)        VSF_MREPEAT53( __MACRO, __PARAM)   __MACRO( 53, __PARAM)
#define VSF_MREPEAT55( __MACRO, __PARAM)        VSF_MREPEAT54( __MACRO, __PARAM)   __MACRO( 54, __PARAM)
#define VSF_MREPEAT56( __MACRO, __PARAM)        VSF_MREPEAT55( __MACRO, __PARAM)   __MACRO( 55, __PARAM)
#define VSF_MREPEAT57( __MACRO, __PARAM)        VSF_MREPEAT56( __MACRO, __PARAM)   __MACRO( 56, __PARAM)
#define VSF_MREPEAT58( __MACRO, __PARAM)        VSF_MREPEAT57( __MACRO, __PARAM)   __MACRO( 57, __PARAM)
#define VSF_MREPEAT59( __MACRO, __PARAM)        VSF_MREPEAT58( __MACRO, __PARAM)   __MACRO( 58, __PARAM)
#define VSF_MREPEAT60( __MACRO, __PARAM)        VSF_MREPEAT59( __MACRO, __PARAM)   __MACRO( 59, __PARAM)
#define VSF_MREPEAT61( __MACRO, __PARAM)        VSF_MREPEAT60( __MACRO, __PARAM)   __MACRO( 60, __PARAM)
#define VSF_MREPEAT62( __MACRO, __PARAM)        VSF_MREPEAT61( __MACRO, __PARAM)   __MACRO( 61, __PARAM)
#define VSF_MREPEAT63( __MACRO, __PARAM)        VSF_MREPEAT62( __MACRO, __PARAM)   __MACRO( 62, __PARAM)
#define VSF_MREPEAT64( __MACRO, __PARAM)        VSF_MREPEAT63( __MACRO, __PARAM)   __MACRO( 63, __PARAM)
#define VSF_MREPEAT65( __MACRO, __PARAM)        VSF_MREPEAT64( __MACRO, __PARAM)   __MACRO( 64, __PARAM)
#define VSF_MREPEAT66( __MACRO, __PARAM)        VSF_MREPEAT65( __MACRO, __PARAM)   __MACRO( 65, __PARAM)
#define VSF_MREPEAT67( __MACRO, __PARAM)        VSF_MREPEAT66( __MACRO, __PARAM)   __MACRO( 66, __PARAM)
#define VSF_MREPEAT68( __MACRO, __PARAM)        VSF_MREPEAT67( __MACRO, __PARAM)   __MACRO( 67, __PARAM)
#define VSF_MREPEAT69( __MACRO, __PARAM)        VSF_MREPEAT68( __MACRO, __PARAM)   __MACRO( 68, __PARAM)
#define VSF_MREPEAT70( __MACRO, __PARAM)        VSF_MREPEAT69( __MACRO, __PARAM)   __MACRO( 69, __PARAM)
#define VSF_MREPEAT71( __MACRO, __PARAM)        VSF_MREPEAT70( __MACRO, __PARAM)   __MACRO( 70, __PARAM)
#define VSF_MREPEAT72( __MACRO, __PARAM)        VSF_MREPEAT71( __MACRO, __PARAM)   __MACRO( 71, __PARAM)
#define VSF_MREPEAT73( __MACRO, __PARAM)        VSF_MREPEAT72( __MACRO, __PARAM)   __MACRO( 72, __PARAM)
#define VSF_MREPEAT74( __MACRO, __PARAM)        VSF_MREPEAT73( __MACRO, __PARAM)   __MACRO( 73, __PARAM)
#define VSF_MREPEAT75( __MACRO, __PARAM)        VSF_MREPEAT74( __MACRO, __PARAM)   __MACRO( 74, __PARAM)
#define VSF_MREPEAT76( __MACRO, __PARAM)        VSF_MREPEAT75( __MACRO, __PARAM)   __MACRO( 75, __PARAM)
#define VSF_MREPEAT77( __MACRO, __PARAM)        VSF_MREPEAT76( __MACRO, __PARAM)   __MACRO( 76, __PARAM)
#define VSF_MREPEAT78( __MACRO, __PARAM)        VSF_MREPEAT77( __MACRO, __PARAM)   __MACRO( 77, __PARAM)
#define VSF_MREPEAT79( __MACRO, __PARAM)        VSF_MREPEAT78( __MACRO, __PARAM)   __MACRO( 78, __PARAM)
#define VSF_MREPEAT80( __MACRO, __PARAM)        VSF_MREPEAT79( __MACRO, __PARAM)   __MACRO( 79, __PARAM)
#define VSF_MREPEAT81( __MACRO, __PARAM)        VSF_MREPEAT80( __MACRO, __PARAM)   __MACRO( 80, __PARAM)
#define VSF_MREPEAT82( __MACRO, __PARAM)        VSF_MREPEAT81( __MACRO, __PARAM)   __MACRO( 81, __PARAM)
#define VSF_MREPEAT83( __MACRO, __PARAM)        VSF_MREPEAT82( __MACRO, __PARAM)   __MACRO( 82, __PARAM)
#define VSF_MREPEAT84( __MACRO, __PARAM)        VSF_MREPEAT83( __MACRO, __PARAM)   __MACRO( 83, __PARAM)
#define VSF_MREPEAT85( __MACRO, __PARAM)        VSF_MREPEAT84( __MACRO, __PARAM)   __MACRO( 84, __PARAM)
#define VSF_MREPEAT86( __MACRO, __PARAM)        VSF_MREPEAT85( __MACRO, __PARAM)   __MACRO( 85, __PARAM)
#define VSF_MREPEAT87( __MACRO, __PARAM)        VSF_MREPEAT86( __MACRO, __PARAM)   __MACRO( 86, __PARAM)
#define VSF_MREPEAT88( __MACRO, __PARAM)        VSF_MREPEAT87( __MACRO, __PARAM)   __MACRO( 87, __PARAM)
#define VSF_MREPEAT89( __MACRO, __PARAM)        VSF_MREPEAT88( __MACRO, __PARAM)   __MACRO( 88, __PARAM)
#define VSF_MREPEAT90( __MACRO, __PARAM)        VSF_MREPEAT89( __MACRO, __PARAM)   __MACRO( 89, __PARAM)
#define VSF_MREPEAT91( __MACRO, __PARAM)        VSF_MREPEAT90( __MACRO, __PARAM)   __MACRO( 90, __PARAM)
#define VSF_MREPEAT92( __MACRO, __PARAM)        VSF_MREPEAT91( __MACRO, __PARAM)   __MACRO( 91, __PARAM)
#define VSF_MREPEAT93( __MACRO, __PARAM)        VSF_MREPEAT92( __MACRO, __PARAM)   __MACRO( 92, __PARAM)
#define VSF_MREPEAT94( __MACRO, __PARAM)        VSF_MREPEAT93( __MACRO, __PARAM)   __MACRO( 93, __PARAM)
#define VSF_MREPEAT95( __MACRO, __PARAM)        VSF_MREPEAT94( __MACRO, __PARAM)   __MACRO( 94, __PARAM)
#define VSF_MREPEAT96( __MACRO, __PARAM)        VSF_MREPEAT95( __MACRO, __PARAM)   __MACRO( 95, __PARAM)
#define VSF_MREPEAT97( __MACRO, __PARAM)        VSF_MREPEAT96( __MACRO, __PARAM)   __MACRO( 96, __PARAM)
#define VSF_MREPEAT98( __MACRO, __PARAM)        VSF_MREPEAT97( __MACRO, __PARAM)   __MACRO( 97, __PARAM)
#define VSF_MREPEAT99( __MACRO, __PARAM)        VSF_MREPEAT98( __MACRO, __PARAM)   __MACRO( 98, __PARAM)
#define VSF_MREPEAT100(__MACRO, __PARAM)        VSF_MREPEAT99( __MACRO, __PARAM)   __MACRO( 99, __PARAM)
#define VSF_MREPEAT101(__MACRO, __PARAM)        VSF_MREPEAT100(__MACRO, __PARAM)   __MACRO(100, __PARAM)
#define VSF_MREPEAT102(__MACRO, __PARAM)        VSF_MREPEAT101(__MACRO, __PARAM)   __MACRO(101, __PARAM)
#define VSF_MREPEAT103(__MACRO, __PARAM)        VSF_MREPEAT102(__MACRO, __PARAM)   __MACRO(102, __PARAM)
#define VSF_MREPEAT104(__MACRO, __PARAM)        VSF_MREPEAT103(__MACRO, __PARAM)   __MACRO(103, __PARAM)
#define VSF_MREPEAT105(__MACRO, __PARAM)        VSF_MREPEAT104(__MACRO, __PARAM)   __MACRO(104, __PARAM)
#define VSF_MREPEAT106(__MACRO, __PARAM)        VSF_MREPEAT105(__MACRO, __PARAM)   __MACRO(105, __PARAM)
#define VSF_MREPEAT107(__MACRO, __PARAM)        VSF_MREPEAT106(__MACRO, __PARAM)   __MACRO(106, __PARAM)
#define VSF_MREPEAT108(__MACRO, __PARAM)        VSF_MREPEAT107(__MACRO, __PARAM)   __MACRO(107, __PARAM)
#define VSF_MREPEAT109(__MACRO, __PARAM)        VSF_MREPEAT108(__MACRO, __PARAM)   __MACRO(108, __PARAM)
#define VSF_MREPEAT110(__MACRO, __PARAM)        VSF_MREPEAT109(__MACRO, __PARAM)   __MACRO(109, __PARAM)
#define VSF_MREPEAT111(__MACRO, __PARAM)        VSF_MREPEAT110(__MACRO, __PARAM)   __MACRO(110, __PARAM)
#define VSF_MREPEAT112(__MACRO, __PARAM)        VSF_MREPEAT111(__MACRO, __PARAM)   __MACRO(111, __PARAM)
#define VSF_MREPEAT113(__MACRO, __PARAM)        VSF_MREPEAT112(__MACRO, __PARAM)   __MACRO(112, __PARAM)
#define VSF_MREPEAT114(__MACRO, __PARAM)        VSF_MREPEAT113(__MACRO, __PARAM)   __MACRO(113, __PARAM)
#define VSF_MREPEAT115(__MACRO, __PARAM)        VSF_MREPEAT114(__MACRO, __PARAM)   __MACRO(114, __PARAM)
#define VSF_MREPEAT116(__MACRO, __PARAM)        VSF_MREPEAT115(__MACRO, __PARAM)   __MACRO(115, __PARAM)
#define VSF_MREPEAT117(__MACRO, __PARAM)        VSF_MREPEAT116(__MACRO, __PARAM)   __MACRO(116, __PARAM)
#define VSF_MREPEAT118(__MACRO, __PARAM)        VSF_MREPEAT117(__MACRO, __PARAM)   __MACRO(117, __PARAM)
#define VSF_MREPEAT119(__MACRO, __PARAM)        VSF_MREPEAT118(__MACRO, __PARAM)   __MACRO(118, __PARAM)
#define VSF_MREPEAT120(__MACRO, __PARAM)        VSF_MREPEAT119(__MACRO, __PARAM)   __MACRO(119, __PARAM)
#define VSF_MREPEAT121(__MACRO, __PARAM)        VSF_MREPEAT120(__MACRO, __PARAM)   __MACRO(120, __PARAM)
#define VSF_MREPEAT122(__MACRO, __PARAM)        VSF_MREPEAT121(__MACRO, __PARAM)   __MACRO(121, __PARAM)
#define VSF_MREPEAT123(__MACRO, __PARAM)        VSF_MREPEAT122(__MACRO, __PARAM)   __MACRO(122, __PARAM)
#define VSF_MREPEAT124(__MACRO, __PARAM)        VSF_MREPEAT123(__MACRO, __PARAM)   __MACRO(123, __PARAM)
#define VSF_MREPEAT125(__MACRO, __PARAM)        VSF_MREPEAT124(__MACRO, __PARAM)   __MACRO(124, __PARAM)
#define VSF_MREPEAT126(__MACRO, __PARAM)        VSF_MREPEAT125(__MACRO, __PARAM)   __MACRO(125, __PARAM)
#define VSF_MREPEAT127(__MACRO, __PARAM)        VSF_MREPEAT126(__MACRO, __PARAM)   __MACRO(126, __PARAM)
#define VSF_MREPEAT128(__MACRO, __PARAM)        VSF_MREPEAT127(__MACRO, __PARAM)   __MACRO(127, __PARAM)
#define VSF_MREPEAT129(__MACRO, __PARAM)        VSF_MREPEAT128(__MACRO, __PARAM)   __MACRO(128, __PARAM)
#define VSF_MREPEAT130(__MACRO, __PARAM)        VSF_MREPEAT129(__MACRO, __PARAM)   __MACRO(129, __PARAM)
#define VSF_MREPEAT131(__MACRO, __PARAM)        VSF_MREPEAT130(__MACRO, __PARAM)   __MACRO(130, __PARAM)
#define VSF_MREPEAT132(__MACRO, __PARAM)        VSF_MREPEAT131(__MACRO, __PARAM)   __MACRO(131, __PARAM)
#define VSF_MREPEAT133(__MACRO, __PARAM)        VSF_MREPEAT132(__MACRO, __PARAM)   __MACRO(132, __PARAM)
#define VSF_MREPEAT134(__MACRO, __PARAM)        VSF_MREPEAT133(__MACRO, __PARAM)   __MACRO(133, __PARAM)
#define VSF_MREPEAT135(__MACRO, __PARAM)        VSF_MREPEAT134(__MACRO, __PARAM)   __MACRO(134, __PARAM)
#define VSF_MREPEAT136(__MACRO, __PARAM)        VSF_MREPEAT135(__MACRO, __PARAM)   __MACRO(135, __PARAM)
#define VSF_MREPEAT137(__MACRO, __PARAM)        VSF_MREPEAT136(__MACRO, __PARAM)   __MACRO(136, __PARAM)
#define VSF_MREPEAT138(__MACRO, __PARAM)        VSF_MREPEAT137(__MACRO, __PARAM)   __MACRO(137, __PARAM)
#define VSF_MREPEAT139(__MACRO, __PARAM)        VSF_MREPEAT138(__MACRO, __PARAM)   __MACRO(138, __PARAM)
#define VSF_MREPEAT140(__MACRO, __PARAM)        VSF_MREPEAT139(__MACRO, __PARAM)   __MACRO(139, __PARAM)
#define VSF_MREPEAT141(__MACRO, __PARAM)        VSF_MREPEAT140(__MACRO, __PARAM)   __MACRO(140, __PARAM)
#define VSF_MREPEAT142(__MACRO, __PARAM)        VSF_MREPEAT141(__MACRO, __PARAM)   __MACRO(141, __PARAM)
#define VSF_MREPEAT143(__MACRO, __PARAM)        VSF_MREPEAT142(__MACRO, __PARAM)   __MACRO(142, __PARAM)
#define VSF_MREPEAT144(__MACRO, __PARAM)        VSF_MREPEAT143(__MACRO, __PARAM)   __MACRO(143, __PARAM)
#define VSF_MREPEAT145(__MACRO, __PARAM)        VSF_MREPEAT144(__MACRO, __PARAM)   __MACRO(144, __PARAM)
#define VSF_MREPEAT146(__MACRO, __PARAM)        VSF_MREPEAT145(__MACRO, __PARAM)   __MACRO(145, __PARAM)
#define VSF_MREPEAT147(__MACRO, __PARAM)        VSF_MREPEAT146(__MACRO, __PARAM)   __MACRO(146, __PARAM)
#define VSF_MREPEAT148(__MACRO, __PARAM)        VSF_MREPEAT147(__MACRO, __PARAM)   __MACRO(147, __PARAM)
#define VSF_MREPEAT149(__MACRO, __PARAM)        VSF_MREPEAT148(__MACRO, __PARAM)   __MACRO(148, __PARAM)
#define VSF_MREPEAT150(__MACRO, __PARAM)        VSF_MREPEAT149(__MACRO, __PARAM)   __MACRO(149, __PARAM)
#define VSF_MREPEAT151(__MACRO, __PARAM)        VSF_MREPEAT150(__MACRO, __PARAM)   __MACRO(150, __PARAM)
#define VSF_MREPEAT152(__MACRO, __PARAM)        VSF_MREPEAT151(__MACRO, __PARAM)   __MACRO(151, __PARAM)
#define VSF_MREPEAT153(__MACRO, __PARAM)        VSF_MREPEAT152(__MACRO, __PARAM)   __MACRO(152, __PARAM)
#define VSF_MREPEAT154(__MACRO, __PARAM)        VSF_MREPEAT153(__MACRO, __PARAM)   __MACRO(153, __PARAM)
#define VSF_MREPEAT155(__MACRO, __PARAM)        VSF_MREPEAT154(__MACRO, __PARAM)   __MACRO(154, __PARAM)
#define VSF_MREPEAT156(__MACRO, __PARAM)        VSF_MREPEAT155(__MACRO, __PARAM)   __MACRO(155, __PARAM)
#define VSF_MREPEAT157(__MACRO, __PARAM)        VSF_MREPEAT156(__MACRO, __PARAM)   __MACRO(156, __PARAM)
#define VSF_MREPEAT158(__MACRO, __PARAM)        VSF_MREPEAT157(__MACRO, __PARAM)   __MACRO(157, __PARAM)
#define VSF_MREPEAT159(__MACRO, __PARAM)        VSF_MREPEAT158(__MACRO, __PARAM)   __MACRO(158, __PARAM)
#define VSF_MREPEAT160(__MACRO, __PARAM)        VSF_MREPEAT159(__MACRO, __PARAM)   __MACRO(159, __PARAM)
#define VSF_MREPEAT161(__MACRO, __PARAM)        VSF_MREPEAT160(__MACRO, __PARAM)   __MACRO(160, __PARAM)
#define VSF_MREPEAT162(__MACRO, __PARAM)        VSF_MREPEAT161(__MACRO, __PARAM)   __MACRO(161, __PARAM)
#define VSF_MREPEAT163(__MACRO, __PARAM)        VSF_MREPEAT162(__MACRO, __PARAM)   __MACRO(162, __PARAM)
#define VSF_MREPEAT164(__MACRO, __PARAM)        VSF_MREPEAT163(__MACRO, __PARAM)   __MACRO(163, __PARAM)
#define VSF_MREPEAT165(__MACRO, __PARAM)        VSF_MREPEAT164(__MACRO, __PARAM)   __MACRO(164, __PARAM)
#define VSF_MREPEAT166(__MACRO, __PARAM)        VSF_MREPEAT165(__MACRO, __PARAM)   __MACRO(165, __PARAM)
#define VSF_MREPEAT167(__MACRO, __PARAM)        VSF_MREPEAT166(__MACRO, __PARAM)   __MACRO(166, __PARAM)
#define VSF_MREPEAT168(__MACRO, __PARAM)        VSF_MREPEAT167(__MACRO, __PARAM)   __MACRO(167, __PARAM)
#define VSF_MREPEAT169(__MACRO, __PARAM)        VSF_MREPEAT168(__MACRO, __PARAM)   __MACRO(168, __PARAM)
#define VSF_MREPEAT170(__MACRO, __PARAM)        VSF_MREPEAT169(__MACRO, __PARAM)   __MACRO(169, __PARAM)
#define VSF_MREPEAT171(__MACRO, __PARAM)        VSF_MREPEAT170(__MACRO, __PARAM)   __MACRO(170, __PARAM)
#define VSF_MREPEAT172(__MACRO, __PARAM)        VSF_MREPEAT171(__MACRO, __PARAM)   __MACRO(171, __PARAM)
#define VSF_MREPEAT173(__MACRO, __PARAM)        VSF_MREPEAT172(__MACRO, __PARAM)   __MACRO(172, __PARAM)
#define VSF_MREPEAT174(__MACRO, __PARAM)        VSF_MREPEAT173(__MACRO, __PARAM)   __MACRO(173, __PARAM)
#define VSF_MREPEAT175(__MACRO, __PARAM)        VSF_MREPEAT174(__MACRO, __PARAM)   __MACRO(174, __PARAM)
#define VSF_MREPEAT176(__MACRO, __PARAM)        VSF_MREPEAT175(__MACRO, __PARAM)   __MACRO(175, __PARAM)
#define VSF_MREPEAT177(__MACRO, __PARAM)        VSF_MREPEAT176(__MACRO, __PARAM)   __MACRO(176, __PARAM)
#define VSF_MREPEAT178(__MACRO, __PARAM)        VSF_MREPEAT177(__MACRO, __PARAM)   __MACRO(177, __PARAM)
#define VSF_MREPEAT179(__MACRO, __PARAM)        VSF_MREPEAT178(__MACRO, __PARAM)   __MACRO(178, __PARAM)
#define VSF_MREPEAT180(__MACRO, __PARAM)        VSF_MREPEAT179(__MACRO, __PARAM)   __MACRO(179, __PARAM)
#define VSF_MREPEAT181(__MACRO, __PARAM)        VSF_MREPEAT180(__MACRO, __PARAM)   __MACRO(180, __PARAM)
#define VSF_MREPEAT182(__MACRO, __PARAM)        VSF_MREPEAT181(__MACRO, __PARAM)   __MACRO(181, __PARAM)
#define VSF_MREPEAT183(__MACRO, __PARAM)        VSF_MREPEAT182(__MACRO, __PARAM)   __MACRO(182, __PARAM)
#define VSF_MREPEAT184(__MACRO, __PARAM)        VSF_MREPEAT183(__MACRO, __PARAM)   __MACRO(183, __PARAM)
#define VSF_MREPEAT185(__MACRO, __PARAM)        VSF_MREPEAT184(__MACRO, __PARAM)   __MACRO(184, __PARAM)
#define VSF_MREPEAT186(__MACRO, __PARAM)        VSF_MREPEAT185(__MACRO, __PARAM)   __MACRO(185, __PARAM)
#define VSF_MREPEAT187(__MACRO, __PARAM)        VSF_MREPEAT186(__MACRO, __PARAM)   __MACRO(186, __PARAM)
#define VSF_MREPEAT188(__MACRO, __PARAM)        VSF_MREPEAT187(__MACRO, __PARAM)   __MACRO(187, __PARAM)
#define VSF_MREPEAT189(__MACRO, __PARAM)        VSF_MREPEAT188(__MACRO, __PARAM)   __MACRO(188, __PARAM)
#define VSF_MREPEAT190(__MACRO, __PARAM)        VSF_MREPEAT189(__MACRO, __PARAM)   __MACRO(189, __PARAM)
#define VSF_MREPEAT191(__MACRO, __PARAM)        VSF_MREPEAT190(__MACRO, __PARAM)   __MACRO(190, __PARAM)
#define VSF_MREPEAT192(__MACRO, __PARAM)        VSF_MREPEAT191(__MACRO, __PARAM)   __MACRO(191, __PARAM)
#define VSF_MREPEAT193(__MACRO, __PARAM)        VSF_MREPEAT192(__MACRO, __PARAM)   __MACRO(192, __PARAM)
#define VSF_MREPEAT194(__MACRO, __PARAM)        VSF_MREPEAT193(__MACRO, __PARAM)   __MACRO(193, __PARAM)
#define VSF_MREPEAT195(__MACRO, __PARAM)        VSF_MREPEAT194(__MACRO, __PARAM)   __MACRO(194, __PARAM)
#define VSF_MREPEAT196(__MACRO, __PARAM)        VSF_MREPEAT195(__MACRO, __PARAM)   __MACRO(195, __PARAM)
#define VSF_MREPEAT197(__MACRO, __PARAM)        VSF_MREPEAT196(__MACRO, __PARAM)   __MACRO(196, __PARAM)
#define VSF_MREPEAT198(__MACRO, __PARAM)        VSF_MREPEAT197(__MACRO, __PARAM)   __MACRO(197, __PARAM)
#define VSF_MREPEAT199(__MACRO, __PARAM)        VSF_MREPEAT198(__MACRO, __PARAM)   __MACRO(198, __PARAM)
#define VSF_MREPEAT200(__MACRO, __PARAM)        VSF_MREPEAT199(__MACRO, __PARAM)   __MACRO(199, __PARAM)
#define VSF_MREPEAT201(__MACRO, __PARAM)        VSF_MREPEAT200(__MACRO, __PARAM)   __MACRO(200, __PARAM)
#define VSF_MREPEAT202(__MACRO, __PARAM)        VSF_MREPEAT201(__MACRO, __PARAM)   __MACRO(201, __PARAM)
#define VSF_MREPEAT203(__MACRO, __PARAM)        VSF_MREPEAT202(__MACRO, __PARAM)   __MACRO(202, __PARAM)
#define VSF_MREPEAT204(__MACRO, __PARAM)        VSF_MREPEAT203(__MACRO, __PARAM)   __MACRO(203, __PARAM)
#define VSF_MREPEAT205(__MACRO, __PARAM)        VSF_MREPEAT204(__MACRO, __PARAM)   __MACRO(204, __PARAM)
#define VSF_MREPEAT206(__MACRO, __PARAM)        VSF_MREPEAT205(__MACRO, __PARAM)   __MACRO(205, __PARAM)
#define VSF_MREPEAT207(__MACRO, __PARAM)        VSF_MREPEAT206(__MACRO, __PARAM)   __MACRO(206, __PARAM)
#define VSF_MREPEAT208(__MACRO, __PARAM)        VSF_MREPEAT207(__MACRO, __PARAM)   __MACRO(207, __PARAM)
#define VSF_MREPEAT209(__MACRO, __PARAM)        VSF_MREPEAT208(__MACRO, __PARAM)   __MACRO(208, __PARAM)
#define VSF_MREPEAT210(__MACRO, __PARAM)        VSF_MREPEAT209(__MACRO, __PARAM)   __MACRO(209, __PARAM)
#define VSF_MREPEAT211(__MACRO, __PARAM)        VSF_MREPEAT210(__MACRO, __PARAM)   __MACRO(210, __PARAM)
#define VSF_MREPEAT212(__MACRO, __PARAM)        VSF_MREPEAT211(__MACRO, __PARAM)   __MACRO(211, __PARAM)
#define VSF_MREPEAT213(__MACRO, __PARAM)        VSF_MREPEAT212(__MACRO, __PARAM)   __MACRO(212, __PARAM)
#define VSF_MREPEAT214(__MACRO, __PARAM)        VSF_MREPEAT213(__MACRO, __PARAM)   __MACRO(213, __PARAM)
#define VSF_MREPEAT215(__MACRO, __PARAM)        VSF_MREPEAT214(__MACRO, __PARAM)   __MACRO(214, __PARAM)
#define VSF_MREPEAT216(__MACRO, __PARAM)        VSF_MREPEAT215(__MACRO, __PARAM)   __MACRO(215, __PARAM)
#define VSF_MREPEAT217(__MACRO, __PARAM)        VSF_MREPEAT216(__MACRO, __PARAM)   __MACRO(216, __PARAM)
#define VSF_MREPEAT218(__MACRO, __PARAM)        VSF_MREPEAT217(__MACRO, __PARAM)   __MACRO(217, __PARAM)
#define VSF_MREPEAT219(__MACRO, __PARAM)        VSF_MREPEAT218(__MACRO, __PARAM)   __MACRO(218, __PARAM)
#define VSF_MREPEAT220(__MACRO, __PARAM)        VSF_MREPEAT219(__MACRO, __PARAM)   __MACRO(219, __PARAM)
#define VSF_MREPEAT221(__MACRO, __PARAM)        VSF_MREPEAT220(__MACRO, __PARAM)   __MACRO(220, __PARAM)
#define VSF_MREPEAT222(__MACRO, __PARAM)        VSF_MREPEAT221(__MACRO, __PARAM)   __MACRO(221, __PARAM)
#define VSF_MREPEAT223(__MACRO, __PARAM)        VSF_MREPEAT222(__MACRO, __PARAM)   __MACRO(222, __PARAM)
#define VSF_MREPEAT224(__MACRO, __PARAM)        VSF_MREPEAT223(__MACRO, __PARAM)   __MACRO(223, __PARAM)
#define VSF_MREPEAT225(__MACRO, __PARAM)        VSF_MREPEAT224(__MACRO, __PARAM)   __MACRO(224, __PARAM)
#define VSF_MREPEAT226(__MACRO, __PARAM)        VSF_MREPEAT225(__MACRO, __PARAM)   __MACRO(225, __PARAM)
#define VSF_MREPEAT227(__MACRO, __PARAM)        VSF_MREPEAT226(__MACRO, __PARAM)   __MACRO(226, __PARAM)
#define VSF_MREPEAT228(__MACRO, __PARAM)        VSF_MREPEAT227(__MACRO, __PARAM)   __MACRO(227, __PARAM)
#define VSF_MREPEAT229(__MACRO, __PARAM)        VSF_MREPEAT228(__MACRO, __PARAM)   __MACRO(228, __PARAM)
#define VSF_MREPEAT230(__MACRO, __PARAM)        VSF_MREPEAT229(__MACRO, __PARAM)   __MACRO(229, __PARAM)
#define VSF_MREPEAT231(__MACRO, __PARAM)        VSF_MREPEAT230(__MACRO, __PARAM)   __MACRO(230, __PARAM)
#define VSF_MREPEAT232(__MACRO, __PARAM)        VSF_MREPEAT231(__MACRO, __PARAM)   __MACRO(231, __PARAM)
#define VSF_MREPEAT233(__MACRO, __PARAM)        VSF_MREPEAT232(__MACRO, __PARAM)   __MACRO(232, __PARAM)
#define VSF_MREPEAT234(__MACRO, __PARAM)        VSF_MREPEAT233(__MACRO, __PARAM)   __MACRO(233, __PARAM)
#define VSF_MREPEAT235(__MACRO, __PARAM)        VSF_MREPEAT234(__MACRO, __PARAM)   __MACRO(234, __PARAM)
#define VSF_MREPEAT236(__MACRO, __PARAM)        VSF_MREPEAT235(__MACRO, __PARAM)   __MACRO(235, __PARAM)
#define VSF_MREPEAT237(__MACRO, __PARAM)        VSF_MREPEAT236(__MACRO, __PARAM)   __MACRO(236, __PARAM)
#define VSF_MREPEAT238(__MACRO, __PARAM)        VSF_MREPEAT237(__MACRO, __PARAM)   __MACRO(237, __PARAM)
#define VSF_MREPEAT239(__MACRO, __PARAM)        VSF_MREPEAT238(__MACRO, __PARAM)   __MACRO(238, __PARAM)
#define VSF_MREPEAT240(__MACRO, __PARAM)        VSF_MREPEAT239(__MACRO, __PARAM)   __MACRO(239, __PARAM)
#define VSF_MREPEAT241(__MACRO, __PARAM)        VSF_MREPEAT240(__MACRO, __PARAM)   __MACRO(240, __PARAM)
#define VSF_MREPEAT242(__MACRO, __PARAM)        VSF_MREPEAT241(__MACRO, __PARAM)   __MACRO(241, __PARAM)
#define VSF_MREPEAT243(__MACRO, __PARAM)        VSF_MREPEAT242(__MACRO, __PARAM)   __MACRO(242, __PARAM)
#define VSF_MREPEAT244(__MACRO, __PARAM)        VSF_MREPEAT243(__MACRO, __PARAM)   __MACRO(243, __PARAM)
#define VSF_MREPEAT245(__MACRO, __PARAM)        VSF_MREPEAT244(__MACRO, __PARAM)   __MACRO(244, __PARAM)
#define VSF_MREPEAT246(__MACRO, __PARAM)        VSF_MREPEAT245(__MACRO, __PARAM)   __MACRO(245, __PARAM)
#define VSF_MREPEAT247(__MACRO, __PARAM)        VSF_MREPEAT246(__MACRO, __PARAM)   __MACRO(246, __PARAM)
#define VSF_MREPEAT248(__MACRO, __PARAM)        VSF_MREPEAT247(__MACRO, __PARAM)   __MACRO(247, __PARAM)
#define VSF_MREPEAT249(__MACRO, __PARAM)        VSF_MREPEAT248(__MACRO, __PARAM)   __MACRO(248, __PARAM)
#define VSF_MREPEAT250(__MACRO, __PARAM)        VSF_MREPEAT249(__MACRO, __PARAM)   __MACRO(249, __PARAM)
#define VSF_MREPEAT251(__MACRO, __PARAM)        VSF_MREPEAT250(__MACRO, __PARAM)   __MACRO(250, __PARAM)
#define VSF_MREPEAT252(__MACRO, __PARAM)        VSF_MREPEAT251(__MACRO, __PARAM)   __MACRO(251, __PARAM)
#define VSF_MREPEAT253(__MACRO, __PARAM)        VSF_MREPEAT252(__MACRO, __PARAM)   __MACRO(252, __PARAM)
#define VSF_MREPEAT254(__MACRO, __PARAM)        VSF_MREPEAT253(__MACRO, __PARAM)   __MACRO(253, __PARAM)
#define VSF_MREPEAT255(__MACRO, __PARAM)        VSF_MREPEAT254(__MACRO, __PARAM)   __MACRO(254, __PARAM)
#define VSF_MREPEAT256(__MACRO, __PARAM)        VSF_MREPEAT255(__MACRO, __PARAM)   __MACRO(255, __PARAM)

#else

#define VSF_MREPEAT(__COUNT, __MACRO, ...)      VSF_MCONNECT(VSF_MREPEAT, __COUNT)(__MACRO, ##__VA_ARGS__)

#define VSF_MREPEAT0(  __MACRO, ...)
#define VSF_MREPEAT1(  __MACRO, ...)            VSF_MREPEAT0(  __MACRO, ##__VA_ARGS__)   __MACRO(  0, ##__VA_ARGS__)
#define VSF_MREPEAT2(  __MACRO, ...)            VSF_MREPEAT1(  __MACRO, ##__VA_ARGS__)   __MACRO(  1, ##__VA_ARGS__)
#define VSF_MREPEAT3(  __MACRO, ...)            VSF_MREPEAT2(  __MACRO, ##__VA_ARGS__)   __MACRO(  2, ##__VA_ARGS__)
#define VSF_MREPEAT4(  __MACRO, ...)            VSF_MREPEAT3(  __MACRO, ##__VA_ARGS__)   __MACRO(  3, ##__VA_ARGS__)
#define VSF_MREPEAT5(  __MACRO, ...)            VSF_MREPEAT4(  __MACRO, ##__VA_ARGS__)   __MACRO(  4, ##__VA_ARGS__)
#define VSF_MREPEAT6(  __MACRO, ...)            VSF_MREPEAT5(  __MACRO, ##__VA_ARGS__)   __MACRO(  5, ##__VA_ARGS__)
#define VSF_MREPEAT7(  __MACRO, ...)            VSF_MREPEAT6(  __MACRO, ##__VA_ARGS__)   __MACRO(  6, ##__VA_ARGS__)
#define VSF_MREPEAT8(  __MACRO, ...)            VSF_MREPEAT7(  __MACRO, ##__VA_ARGS__)   __MACRO(  7, ##__VA_ARGS__)
#define VSF_MREPEAT9(  __MACRO, ...)            VSF_MREPEAT8(  __MACRO, ##__VA_ARGS__)   __MACRO(  8, ##__VA_ARGS__)
#define VSF_MREPEAT10( __MACRO, ...)            VSF_MREPEAT9(  __MACRO, ##__VA_ARGS__)   __MACRO(  9, ##__VA_ARGS__)
#define VSF_MREPEAT11( __MACRO, ...)            VSF_MREPEAT10( __MACRO, ##__VA_ARGS__)   __MACRO( 10, ##__VA_ARGS__)
#define VSF_MREPEAT12( __MACRO, ...)            VSF_MREPEAT11( __MACRO, ##__VA_ARGS__)   __MACRO( 11, ##__VA_ARGS__)
#define VSF_MREPEAT13( __MACRO, ...)            VSF_MREPEAT12( __MACRO, ##__VA_ARGS__)   __MACRO( 12, ##__VA_ARGS__)
#define VSF_MREPEAT14( __MACRO, ...)            VSF_MREPEAT13( __MACRO, ##__VA_ARGS__)   __MACRO( 13, ##__VA_ARGS__)
#define VSF_MREPEAT15( __MACRO, ...)            VSF_MREPEAT14( __MACRO, ##__VA_ARGS__)   __MACRO( 14, ##__VA_ARGS__)
#define VSF_MREPEAT16( __MACRO, ...)            VSF_MREPEAT15( __MACRO, ##__VA_ARGS__)   __MACRO( 15, ##__VA_ARGS__)
#define VSF_MREPEAT17( __MACRO, ...)            VSF_MREPEAT16( __MACRO, ##__VA_ARGS__)   __MACRO( 16, ##__VA_ARGS__)
#define VSF_MREPEAT18( __MACRO, ...)            VSF_MREPEAT17( __MACRO, ##__VA_ARGS__)   __MACRO( 17, ##__VA_ARGS__)
#define VSF_MREPEAT19( __MACRO, ...)            VSF_MREPEAT18( __MACRO, ##__VA_ARGS__)   __MACRO( 18, ##__VA_ARGS__)
#define VSF_MREPEAT20( __MACRO, ...)            VSF_MREPEAT19( __MACRO, ##__VA_ARGS__)   __MACRO( 19, ##__VA_ARGS__)
#define VSF_MREPEAT21( __MACRO, ...)            VSF_MREPEAT20( __MACRO, ##__VA_ARGS__)   __MACRO( 20, ##__VA_ARGS__)
#define VSF_MREPEAT22( __MACRO, ...)            VSF_MREPEAT21( __MACRO, ##__VA_ARGS__)   __MACRO( 21, ##__VA_ARGS__)
#define VSF_MREPEAT23( __MACRO, ...)            VSF_MREPEAT22( __MACRO, ##__VA_ARGS__)   __MACRO( 22, ##__VA_ARGS__)
#define VSF_MREPEAT24( __MACRO, ...)            VSF_MREPEAT23( __MACRO, ##__VA_ARGS__)   __MACRO( 23, ##__VA_ARGS__)
#define VSF_MREPEAT25( __MACRO, ...)            VSF_MREPEAT24( __MACRO, ##__VA_ARGS__)   __MACRO( 24, ##__VA_ARGS__)
#define VSF_MREPEAT26( __MACRO, ...)            VSF_MREPEAT25( __MACRO, ##__VA_ARGS__)   __MACRO( 25, ##__VA_ARGS__)
#define VSF_MREPEAT27( __MACRO, ...)            VSF_MREPEAT26( __MACRO, ##__VA_ARGS__)   __MACRO( 26, ##__VA_ARGS__)
#define VSF_MREPEAT28( __MACRO, ...)            VSF_MREPEAT27( __MACRO, ##__VA_ARGS__)   __MACRO( 27, ##__VA_ARGS__)
#define VSF_MREPEAT29( __MACRO, ...)            VSF_MREPEAT28( __MACRO, ##__VA_ARGS__)   __MACRO( 28, ##__VA_ARGS__)
#define VSF_MREPEAT30( __MACRO, ...)            VSF_MREPEAT29( __MACRO, ##__VA_ARGS__)   __MACRO( 29, ##__VA_ARGS__)
#define VSF_MREPEAT31( __MACRO, ...)            VSF_MREPEAT30( __MACRO, ##__VA_ARGS__)   __MACRO( 30, ##__VA_ARGS__)
#define VSF_MREPEAT32( __MACRO, ...)            VSF_MREPEAT31( __MACRO, ##__VA_ARGS__)   __MACRO( 31, ##__VA_ARGS__)
#define VSF_MREPEAT33( __MACRO, ...)            VSF_MREPEAT32( __MACRO, ##__VA_ARGS__)   __MACRO( 32, ##__VA_ARGS__)
#define VSF_MREPEAT34( __MACRO, ...)            VSF_MREPEAT33( __MACRO, ##__VA_ARGS__)   __MACRO( 33, ##__VA_ARGS__)
#define VSF_MREPEAT35( __MACRO, ...)            VSF_MREPEAT34( __MACRO, ##__VA_ARGS__)   __MACRO( 34, ##__VA_ARGS__)
#define VSF_MREPEAT36( __MACRO, ...)            VSF_MREPEAT35( __MACRO, ##__VA_ARGS__)   __MACRO( 35, ##__VA_ARGS__)
#define VSF_MREPEAT37( __MACRO, ...)            VSF_MREPEAT36( __MACRO, ##__VA_ARGS__)   __MACRO( 36, ##__VA_ARGS__)
#define VSF_MREPEAT38( __MACRO, ...)            VSF_MREPEAT37( __MACRO, ##__VA_ARGS__)   __MACRO( 37, ##__VA_ARGS__)
#define VSF_MREPEAT39( __MACRO, ...)            VSF_MREPEAT38( __MACRO, ##__VA_ARGS__)   __MACRO( 38, ##__VA_ARGS__)
#define VSF_MREPEAT40( __MACRO, ...)            VSF_MREPEAT39( __MACRO, ##__VA_ARGS__)   __MACRO( 39, ##__VA_ARGS__)
#define VSF_MREPEAT41( __MACRO, ...)            VSF_MREPEAT40( __MACRO, ##__VA_ARGS__)   __MACRO( 40, ##__VA_ARGS__)
#define VSF_MREPEAT42( __MACRO, ...)            VSF_MREPEAT41( __MACRO, ##__VA_ARGS__)   __MACRO( 41, ##__VA_ARGS__)
#define VSF_MREPEAT43( __MACRO, ...)            VSF_MREPEAT42( __MACRO, ##__VA_ARGS__)   __MACRO( 42, ##__VA_ARGS__)
#define VSF_MREPEAT44( __MACRO, ...)            VSF_MREPEAT43( __MACRO, ##__VA_ARGS__)   __MACRO( 43, ##__VA_ARGS__)
#define VSF_MREPEAT45( __MACRO, ...)            VSF_MREPEAT44( __MACRO, ##__VA_ARGS__)   __MACRO( 44, ##__VA_ARGS__)
#define VSF_MREPEAT46( __MACRO, ...)            VSF_MREPEAT45( __MACRO, ##__VA_ARGS__)   __MACRO( 45, ##__VA_ARGS__)
#define VSF_MREPEAT47( __MACRO, ...)            VSF_MREPEAT46( __MACRO, ##__VA_ARGS__)   __MACRO( 46, ##__VA_ARGS__)
#define VSF_MREPEAT48( __MACRO, ...)            VSF_MREPEAT47( __MACRO, ##__VA_ARGS__)   __MACRO( 47, ##__VA_ARGS__)
#define VSF_MREPEAT49( __MACRO, ...)            VSF_MREPEAT48( __MACRO, ##__VA_ARGS__)   __MACRO( 48, ##__VA_ARGS__)
#define VSF_MREPEAT50( __MACRO, ...)            VSF_MREPEAT49( __MACRO, ##__VA_ARGS__)   __MACRO( 49, ##__VA_ARGS__)
#define VSF_MREPEAT51( __MACRO, ...)            VSF_MREPEAT50( __MACRO, ##__VA_ARGS__)   __MACRO( 50, ##__VA_ARGS__)
#define VSF_MREPEAT52( __MACRO, ...)            VSF_MREPEAT51( __MACRO, ##__VA_ARGS__)   __MACRO( 51, ##__VA_ARGS__)
#define VSF_MREPEAT53( __MACRO, ...)            VSF_MREPEAT52( __MACRO, ##__VA_ARGS__)   __MACRO( 52, ##__VA_ARGS__)
#define VSF_MREPEAT54( __MACRO, ...)            VSF_MREPEAT53( __MACRO, ##__VA_ARGS__)   __MACRO( 53, ##__VA_ARGS__)
#define VSF_MREPEAT55( __MACRO, ...)            VSF_MREPEAT54( __MACRO, ##__VA_ARGS__)   __MACRO( 54, ##__VA_ARGS__)
#define VSF_MREPEAT56( __MACRO, ...)            VSF_MREPEAT55( __MACRO, ##__VA_ARGS__)   __MACRO( 55, ##__VA_ARGS__)
#define VSF_MREPEAT57( __MACRO, ...)            VSF_MREPEAT56( __MACRO, ##__VA_ARGS__)   __MACRO( 56, ##__VA_ARGS__)
#define VSF_MREPEAT58( __MACRO, ...)            VSF_MREPEAT57( __MACRO, ##__VA_ARGS__)   __MACRO( 57, ##__VA_ARGS__)
#define VSF_MREPEAT59( __MACRO, ...)            VSF_MREPEAT58( __MACRO, ##__VA_ARGS__)   __MACRO( 58, ##__VA_ARGS__)
#define VSF_MREPEAT60( __MACRO, ...)            VSF_MREPEAT59( __MACRO, ##__VA_ARGS__)   __MACRO( 59, ##__VA_ARGS__)
#define VSF_MREPEAT61( __MACRO, ...)            VSF_MREPEAT60( __MACRO, ##__VA_ARGS__)   __MACRO( 60, ##__VA_ARGS__)
#define VSF_MREPEAT62( __MACRO, ...)            VSF_MREPEAT61( __MACRO, ##__VA_ARGS__)   __MACRO( 61, ##__VA_ARGS__)
#define VSF_MREPEAT63( __MACRO, ...)            VSF_MREPEAT62( __MACRO, ##__VA_ARGS__)   __MACRO( 62, ##__VA_ARGS__)
#define VSF_MREPEAT64( __MACRO, ...)            VSF_MREPEAT63( __MACRO, ##__VA_ARGS__)   __MACRO( 63, ##__VA_ARGS__)
#define VSF_MREPEAT65( __MACRO, ...)            VSF_MREPEAT64( __MACRO, ##__VA_ARGS__)   __MACRO( 64, ##__VA_ARGS__)
#define VSF_MREPEAT66( __MACRO, ...)            VSF_MREPEAT65( __MACRO, ##__VA_ARGS__)   __MACRO( 65, ##__VA_ARGS__)
#define VSF_MREPEAT67( __MACRO, ...)            VSF_MREPEAT66( __MACRO, ##__VA_ARGS__)   __MACRO( 66, ##__VA_ARGS__)
#define VSF_MREPEAT68( __MACRO, ...)            VSF_MREPEAT67( __MACRO, ##__VA_ARGS__)   __MACRO( 67, ##__VA_ARGS__)
#define VSF_MREPEAT69( __MACRO, ...)            VSF_MREPEAT68( __MACRO, ##__VA_ARGS__)   __MACRO( 68, ##__VA_ARGS__)
#define VSF_MREPEAT70( __MACRO, ...)            VSF_MREPEAT69( __MACRO, ##__VA_ARGS__)   __MACRO( 69, ##__VA_ARGS__)
#define VSF_MREPEAT71( __MACRO, ...)            VSF_MREPEAT70( __MACRO, ##__VA_ARGS__)   __MACRO( 70, ##__VA_ARGS__)
#define VSF_MREPEAT72( __MACRO, ...)            VSF_MREPEAT71( __MACRO, ##__VA_ARGS__)   __MACRO( 71, ##__VA_ARGS__)
#define VSF_MREPEAT73( __MACRO, ...)            VSF_MREPEAT72( __MACRO, ##__VA_ARGS__)   __MACRO( 72, ##__VA_ARGS__)
#define VSF_MREPEAT74( __MACRO, ...)            VSF_MREPEAT73( __MACRO, ##__VA_ARGS__)   __MACRO( 73, ##__VA_ARGS__)
#define VSF_MREPEAT75( __MACRO, ...)            VSF_MREPEAT74( __MACRO, ##__VA_ARGS__)   __MACRO( 74, ##__VA_ARGS__)
#define VSF_MREPEAT76( __MACRO, ...)            VSF_MREPEAT75( __MACRO, ##__VA_ARGS__)   __MACRO( 75, ##__VA_ARGS__)
#define VSF_MREPEAT77( __MACRO, ...)            VSF_MREPEAT76( __MACRO, ##__VA_ARGS__)   __MACRO( 76, ##__VA_ARGS__)
#define VSF_MREPEAT78( __MACRO, ...)            VSF_MREPEAT77( __MACRO, ##__VA_ARGS__)   __MACRO( 77, ##__VA_ARGS__)
#define VSF_MREPEAT79( __MACRO, ...)            VSF_MREPEAT78( __MACRO, ##__VA_ARGS__)   __MACRO( 78, ##__VA_ARGS__)
#define VSF_MREPEAT80( __MACRO, ...)            VSF_MREPEAT79( __MACRO, ##__VA_ARGS__)   __MACRO( 79, ##__VA_ARGS__)
#define VSF_MREPEAT81( __MACRO, ...)            VSF_MREPEAT80( __MACRO, ##__VA_ARGS__)   __MACRO( 80, ##__VA_ARGS__)
#define VSF_MREPEAT82( __MACRO, ...)            VSF_MREPEAT81( __MACRO, ##__VA_ARGS__)   __MACRO( 81, ##__VA_ARGS__)
#define VSF_MREPEAT83( __MACRO, ...)            VSF_MREPEAT82( __MACRO, ##__VA_ARGS__)   __MACRO( 82, ##__VA_ARGS__)
#define VSF_MREPEAT84( __MACRO, ...)            VSF_MREPEAT83( __MACRO, ##__VA_ARGS__)   __MACRO( 83, ##__VA_ARGS__)
#define VSF_MREPEAT85( __MACRO, ...)            VSF_MREPEAT84( __MACRO, ##__VA_ARGS__)   __MACRO( 84, ##__VA_ARGS__)
#define VSF_MREPEAT86( __MACRO, ...)            VSF_MREPEAT85( __MACRO, ##__VA_ARGS__)   __MACRO( 85, ##__VA_ARGS__)
#define VSF_MREPEAT87( __MACRO, ...)            VSF_MREPEAT86( __MACRO, ##__VA_ARGS__)   __MACRO( 86, ##__VA_ARGS__)
#define VSF_MREPEAT88( __MACRO, ...)            VSF_MREPEAT87( __MACRO, ##__VA_ARGS__)   __MACRO( 87, ##__VA_ARGS__)
#define VSF_MREPEAT89( __MACRO, ...)            VSF_MREPEAT88( __MACRO, ##__VA_ARGS__)   __MACRO( 88, ##__VA_ARGS__)
#define VSF_MREPEAT90( __MACRO, ...)            VSF_MREPEAT89( __MACRO, ##__VA_ARGS__)   __MACRO( 89, ##__VA_ARGS__)
#define VSF_MREPEAT91( __MACRO, ...)            VSF_MREPEAT90( __MACRO, ##__VA_ARGS__)   __MACRO( 90, ##__VA_ARGS__)
#define VSF_MREPEAT92( __MACRO, ...)            VSF_MREPEAT91( __MACRO, ##__VA_ARGS__)   __MACRO( 91, ##__VA_ARGS__)
#define VSF_MREPEAT93( __MACRO, ...)            VSF_MREPEAT92( __MACRO, ##__VA_ARGS__)   __MACRO( 92, ##__VA_ARGS__)
#define VSF_MREPEAT94( __MACRO, ...)            VSF_MREPEAT93( __MACRO, ##__VA_ARGS__)   __MACRO( 93, ##__VA_ARGS__)
#define VSF_MREPEAT95( __MACRO, ...)            VSF_MREPEAT94( __MACRO, ##__VA_ARGS__)   __MACRO( 94, ##__VA_ARGS__)
#define VSF_MREPEAT96( __MACRO, ...)            VSF_MREPEAT95( __MACRO, ##__VA_ARGS__)   __MACRO( 95, ##__VA_ARGS__)
#define VSF_MREPEAT97( __MACRO, ...)            VSF_MREPEAT96( __MACRO, ##__VA_ARGS__)   __MACRO( 96, ##__VA_ARGS__)
#define VSF_MREPEAT98( __MACRO, ...)            VSF_MREPEAT97( __MACRO, ##__VA_ARGS__)   __MACRO( 97, ##__VA_ARGS__)
#define VSF_MREPEAT99( __MACRO, ...)            VSF_MREPEAT98( __MACRO, ##__VA_ARGS__)   __MACRO( 98, ##__VA_ARGS__)
#define VSF_MREPEAT100(__MACRO, ...)            VSF_MREPEAT99( __MACRO, ##__VA_ARGS__)   __MACRO( 99, ##__VA_ARGS__)
#define VSF_MREPEAT101(__MACRO, ...)            VSF_MREPEAT100(__MACRO, ##__VA_ARGS__)   __MACRO(100, ##__VA_ARGS__)
#define VSF_MREPEAT102(__MACRO, ...)            VSF_MREPEAT101(__MACRO, ##__VA_ARGS__)   __MACRO(101, ##__VA_ARGS__)
#define VSF_MREPEAT103(__MACRO, ...)            VSF_MREPEAT102(__MACRO, ##__VA_ARGS__)   __MACRO(102, ##__VA_ARGS__)
#define VSF_MREPEAT104(__MACRO, ...)            VSF_MREPEAT103(__MACRO, ##__VA_ARGS__)   __MACRO(103, ##__VA_ARGS__)
#define VSF_MREPEAT105(__MACRO, ...)            VSF_MREPEAT104(__MACRO, ##__VA_ARGS__)   __MACRO(104, ##__VA_ARGS__)
#define VSF_MREPEAT106(__MACRO, ...)            VSF_MREPEAT105(__MACRO, ##__VA_ARGS__)   __MACRO(105, ##__VA_ARGS__)
#define VSF_MREPEAT107(__MACRO, ...)            VSF_MREPEAT106(__MACRO, ##__VA_ARGS__)   __MACRO(106, ##__VA_ARGS__)
#define VSF_MREPEAT108(__MACRO, ...)            VSF_MREPEAT107(__MACRO, ##__VA_ARGS__)   __MACRO(107, ##__VA_ARGS__)
#define VSF_MREPEAT109(__MACRO, ...)            VSF_MREPEAT108(__MACRO, ##__VA_ARGS__)   __MACRO(108, ##__VA_ARGS__)
#define VSF_MREPEAT110(__MACRO, ...)            VSF_MREPEAT109(__MACRO, ##__VA_ARGS__)   __MACRO(109, ##__VA_ARGS__)
#define VSF_MREPEAT111(__MACRO, ...)            VSF_MREPEAT110(__MACRO, ##__VA_ARGS__)   __MACRO(110, ##__VA_ARGS__)
#define VSF_MREPEAT112(__MACRO, ...)            VSF_MREPEAT111(__MACRO, ##__VA_ARGS__)   __MACRO(111, ##__VA_ARGS__)
#define VSF_MREPEAT113(__MACRO, ...)            VSF_MREPEAT112(__MACRO, ##__VA_ARGS__)   __MACRO(112, ##__VA_ARGS__)
#define VSF_MREPEAT114(__MACRO, ...)            VSF_MREPEAT113(__MACRO, ##__VA_ARGS__)   __MACRO(113, ##__VA_ARGS__)
#define VSF_MREPEAT115(__MACRO, ...)            VSF_MREPEAT114(__MACRO, ##__VA_ARGS__)   __MACRO(114, ##__VA_ARGS__)
#define VSF_MREPEAT116(__MACRO, ...)            VSF_MREPEAT115(__MACRO, ##__VA_ARGS__)   __MACRO(115, ##__VA_ARGS__)
#define VSF_MREPEAT117(__MACRO, ...)            VSF_MREPEAT116(__MACRO, ##__VA_ARGS__)   __MACRO(116, ##__VA_ARGS__)
#define VSF_MREPEAT118(__MACRO, ...)            VSF_MREPEAT117(__MACRO, ##__VA_ARGS__)   __MACRO(117, ##__VA_ARGS__)
#define VSF_MREPEAT119(__MACRO, ...)            VSF_MREPEAT118(__MACRO, ##__VA_ARGS__)   __MACRO(118, ##__VA_ARGS__)
#define VSF_MREPEAT120(__MACRO, ...)            VSF_MREPEAT119(__MACRO, ##__VA_ARGS__)   __MACRO(119, ##__VA_ARGS__)
#define VSF_MREPEAT121(__MACRO, ...)            VSF_MREPEAT120(__MACRO, ##__VA_ARGS__)   __MACRO(120, ##__VA_ARGS__)
#define VSF_MREPEAT122(__MACRO, ...)            VSF_MREPEAT121(__MACRO, ##__VA_ARGS__)   __MACRO(121, ##__VA_ARGS__)
#define VSF_MREPEAT123(__MACRO, ...)            VSF_MREPEAT122(__MACRO, ##__VA_ARGS__)   __MACRO(122, ##__VA_ARGS__)
#define VSF_MREPEAT124(__MACRO, ...)            VSF_MREPEAT123(__MACRO, ##__VA_ARGS__)   __MACRO(123, ##__VA_ARGS__)
#define VSF_MREPEAT125(__MACRO, ...)            VSF_MREPEAT124(__MACRO, ##__VA_ARGS__)   __MACRO(124, ##__VA_ARGS__)
#define VSF_MREPEAT126(__MACRO, ...)            VSF_MREPEAT125(__MACRO, ##__VA_ARGS__)   __MACRO(125, ##__VA_ARGS__)
#define VSF_MREPEAT127(__MACRO, ...)            VSF_MREPEAT126(__MACRO, ##__VA_ARGS__)   __MACRO(126, ##__VA_ARGS__)
#define VSF_MREPEAT128(__MACRO, ...)            VSF_MREPEAT127(__MACRO, ##__VA_ARGS__)   __MACRO(127, ##__VA_ARGS__)
#define VSF_MREPEAT129(__MACRO, ...)            VSF_MREPEAT128(__MACRO, ##__VA_ARGS__)   __MACRO(128, ##__VA_ARGS__)
#define VSF_MREPEAT130(__MACRO, ...)            VSF_MREPEAT129(__MACRO, ##__VA_ARGS__)   __MACRO(129, ##__VA_ARGS__)
#define VSF_MREPEAT131(__MACRO, ...)            VSF_MREPEAT130(__MACRO, ##__VA_ARGS__)   __MACRO(130, ##__VA_ARGS__)
#define VSF_MREPEAT132(__MACRO, ...)            VSF_MREPEAT131(__MACRO, ##__VA_ARGS__)   __MACRO(131, ##__VA_ARGS__)
#define VSF_MREPEAT133(__MACRO, ...)            VSF_MREPEAT132(__MACRO, ##__VA_ARGS__)   __MACRO(132, ##__VA_ARGS__)
#define VSF_MREPEAT134(__MACRO, ...)            VSF_MREPEAT133(__MACRO, ##__VA_ARGS__)   __MACRO(133, ##__VA_ARGS__)
#define VSF_MREPEAT135(__MACRO, ...)            VSF_MREPEAT134(__MACRO, ##__VA_ARGS__)   __MACRO(134, ##__VA_ARGS__)
#define VSF_MREPEAT136(__MACRO, ...)            VSF_MREPEAT135(__MACRO, ##__VA_ARGS__)   __MACRO(135, ##__VA_ARGS__)
#define VSF_MREPEAT137(__MACRO, ...)            VSF_MREPEAT136(__MACRO, ##__VA_ARGS__)   __MACRO(136, ##__VA_ARGS__)
#define VSF_MREPEAT138(__MACRO, ...)            VSF_MREPEAT137(__MACRO, ##__VA_ARGS__)   __MACRO(137, ##__VA_ARGS__)
#define VSF_MREPEAT139(__MACRO, ...)            VSF_MREPEAT138(__MACRO, ##__VA_ARGS__)   __MACRO(138, ##__VA_ARGS__)
#define VSF_MREPEAT140(__MACRO, ...)            VSF_MREPEAT139(__MACRO, ##__VA_ARGS__)   __MACRO(139, ##__VA_ARGS__)
#define VSF_MREPEAT141(__MACRO, ...)            VSF_MREPEAT140(__MACRO, ##__VA_ARGS__)   __MACRO(140, ##__VA_ARGS__)
#define VSF_MREPEAT142(__MACRO, ...)            VSF_MREPEAT141(__MACRO, ##__VA_ARGS__)   __MACRO(141, ##__VA_ARGS__)
#define VSF_MREPEAT143(__MACRO, ...)            VSF_MREPEAT142(__MACRO, ##__VA_ARGS__)   __MACRO(142, ##__VA_ARGS__)
#define VSF_MREPEAT144(__MACRO, ...)            VSF_MREPEAT143(__MACRO, ##__VA_ARGS__)   __MACRO(143, ##__VA_ARGS__)
#define VSF_MREPEAT145(__MACRO, ...)            VSF_MREPEAT144(__MACRO, ##__VA_ARGS__)   __MACRO(144, ##__VA_ARGS__)
#define VSF_MREPEAT146(__MACRO, ...)            VSF_MREPEAT145(__MACRO, ##__VA_ARGS__)   __MACRO(145, ##__VA_ARGS__)
#define VSF_MREPEAT147(__MACRO, ...)            VSF_MREPEAT146(__MACRO, ##__VA_ARGS__)   __MACRO(146, ##__VA_ARGS__)
#define VSF_MREPEAT148(__MACRO, ...)            VSF_MREPEAT147(__MACRO, ##__VA_ARGS__)   __MACRO(147, ##__VA_ARGS__)
#define VSF_MREPEAT149(__MACRO, ...)            VSF_MREPEAT148(__MACRO, ##__VA_ARGS__)   __MACRO(148, ##__VA_ARGS__)
#define VSF_MREPEAT150(__MACRO, ...)            VSF_MREPEAT149(__MACRO, ##__VA_ARGS__)   __MACRO(149, ##__VA_ARGS__)
#define VSF_MREPEAT151(__MACRO, ...)            VSF_MREPEAT150(__MACRO, ##__VA_ARGS__)   __MACRO(150, ##__VA_ARGS__)
#define VSF_MREPEAT152(__MACRO, ...)            VSF_MREPEAT151(__MACRO, ##__VA_ARGS__)   __MACRO(151, ##__VA_ARGS__)
#define VSF_MREPEAT153(__MACRO, ...)            VSF_MREPEAT152(__MACRO, ##__VA_ARGS__)   __MACRO(152, ##__VA_ARGS__)
#define VSF_MREPEAT154(__MACRO, ...)            VSF_MREPEAT153(__MACRO, ##__VA_ARGS__)   __MACRO(153, ##__VA_ARGS__)
#define VSF_MREPEAT155(__MACRO, ...)            VSF_MREPEAT154(__MACRO, ##__VA_ARGS__)   __MACRO(154, ##__VA_ARGS__)
#define VSF_MREPEAT156(__MACRO, ...)            VSF_MREPEAT155(__MACRO, ##__VA_ARGS__)   __MACRO(155, ##__VA_ARGS__)
#define VSF_MREPEAT157(__MACRO, ...)            VSF_MREPEAT156(__MACRO, ##__VA_ARGS__)   __MACRO(156, ##__VA_ARGS__)
#define VSF_MREPEAT158(__MACRO, ...)            VSF_MREPEAT157(__MACRO, ##__VA_ARGS__)   __MACRO(157, ##__VA_ARGS__)
#define VSF_MREPEAT159(__MACRO, ...)            VSF_MREPEAT158(__MACRO, ##__VA_ARGS__)   __MACRO(158, ##__VA_ARGS__)
#define VSF_MREPEAT160(__MACRO, ...)            VSF_MREPEAT159(__MACRO, ##__VA_ARGS__)   __MACRO(159, ##__VA_ARGS__)
#define VSF_MREPEAT161(__MACRO, ...)            VSF_MREPEAT160(__MACRO, ##__VA_ARGS__)   __MACRO(160, ##__VA_ARGS__)
#define VSF_MREPEAT162(__MACRO, ...)            VSF_MREPEAT161(__MACRO, ##__VA_ARGS__)   __MACRO(161, ##__VA_ARGS__)
#define VSF_MREPEAT163(__MACRO, ...)            VSF_MREPEAT162(__MACRO, ##__VA_ARGS__)   __MACRO(162, ##__VA_ARGS__)
#define VSF_MREPEAT164(__MACRO, ...)            VSF_MREPEAT163(__MACRO, ##__VA_ARGS__)   __MACRO(163, ##__VA_ARGS__)
#define VSF_MREPEAT165(__MACRO, ...)            VSF_MREPEAT164(__MACRO, ##__VA_ARGS__)   __MACRO(164, ##__VA_ARGS__)
#define VSF_MREPEAT166(__MACRO, ...)            VSF_MREPEAT165(__MACRO, ##__VA_ARGS__)   __MACRO(165, ##__VA_ARGS__)
#define VSF_MREPEAT167(__MACRO, ...)            VSF_MREPEAT166(__MACRO, ##__VA_ARGS__)   __MACRO(166, ##__VA_ARGS__)
#define VSF_MREPEAT168(__MACRO, ...)            VSF_MREPEAT167(__MACRO, ##__VA_ARGS__)   __MACRO(167, ##__VA_ARGS__)
#define VSF_MREPEAT169(__MACRO, ...)            VSF_MREPEAT168(__MACRO, ##__VA_ARGS__)   __MACRO(168, ##__VA_ARGS__)
#define VSF_MREPEAT170(__MACRO, ...)            VSF_MREPEAT169(__MACRO, ##__VA_ARGS__)   __MACRO(169, ##__VA_ARGS__)
#define VSF_MREPEAT171(__MACRO, ...)            VSF_MREPEAT170(__MACRO, ##__VA_ARGS__)   __MACRO(170, ##__VA_ARGS__)
#define VSF_MREPEAT172(__MACRO, ...)            VSF_MREPEAT171(__MACRO, ##__VA_ARGS__)   __MACRO(171, ##__VA_ARGS__)
#define VSF_MREPEAT173(__MACRO, ...)            VSF_MREPEAT172(__MACRO, ##__VA_ARGS__)   __MACRO(172, ##__VA_ARGS__)
#define VSF_MREPEAT174(__MACRO, ...)            VSF_MREPEAT173(__MACRO, ##__VA_ARGS__)   __MACRO(173, ##__VA_ARGS__)
#define VSF_MREPEAT175(__MACRO, ...)            VSF_MREPEAT174(__MACRO, ##__VA_ARGS__)   __MACRO(174, ##__VA_ARGS__)
#define VSF_MREPEAT176(__MACRO, ...)            VSF_MREPEAT175(__MACRO, ##__VA_ARGS__)   __MACRO(175, ##__VA_ARGS__)
#define VSF_MREPEAT177(__MACRO, ...)            VSF_MREPEAT176(__MACRO, ##__VA_ARGS__)   __MACRO(176, ##__VA_ARGS__)
#define VSF_MREPEAT178(__MACRO, ...)            VSF_MREPEAT177(__MACRO, ##__VA_ARGS__)   __MACRO(177, ##__VA_ARGS__)
#define VSF_MREPEAT179(__MACRO, ...)            VSF_MREPEAT178(__MACRO, ##__VA_ARGS__)   __MACRO(178, ##__VA_ARGS__)
#define VSF_MREPEAT180(__MACRO, ...)            VSF_MREPEAT179(__MACRO, ##__VA_ARGS__)   __MACRO(179, ##__VA_ARGS__)
#define VSF_MREPEAT181(__MACRO, ...)            VSF_MREPEAT180(__MACRO, ##__VA_ARGS__)   __MACRO(180, ##__VA_ARGS__)
#define VSF_MREPEAT182(__MACRO, ...)            VSF_MREPEAT181(__MACRO, ##__VA_ARGS__)   __MACRO(181, ##__VA_ARGS__)
#define VSF_MREPEAT183(__MACRO, ...)            VSF_MREPEAT182(__MACRO, ##__VA_ARGS__)   __MACRO(182, ##__VA_ARGS__)
#define VSF_MREPEAT184(__MACRO, ...)            VSF_MREPEAT183(__MACRO, ##__VA_ARGS__)   __MACRO(183, ##__VA_ARGS__)
#define VSF_MREPEAT185(__MACRO, ...)            VSF_MREPEAT184(__MACRO, ##__VA_ARGS__)   __MACRO(184, ##__VA_ARGS__)
#define VSF_MREPEAT186(__MACRO, ...)            VSF_MREPEAT185(__MACRO, ##__VA_ARGS__)   __MACRO(185, ##__VA_ARGS__)
#define VSF_MREPEAT187(__MACRO, ...)            VSF_MREPEAT186(__MACRO, ##__VA_ARGS__)   __MACRO(186, ##__VA_ARGS__)
#define VSF_MREPEAT188(__MACRO, ...)            VSF_MREPEAT187(__MACRO, ##__VA_ARGS__)   __MACRO(187, ##__VA_ARGS__)
#define VSF_MREPEAT189(__MACRO, ...)            VSF_MREPEAT188(__MACRO, ##__VA_ARGS__)   __MACRO(188, ##__VA_ARGS__)
#define VSF_MREPEAT190(__MACRO, ...)            VSF_MREPEAT189(__MACRO, ##__VA_ARGS__)   __MACRO(189, ##__VA_ARGS__)
#define VSF_MREPEAT191(__MACRO, ...)            VSF_MREPEAT190(__MACRO, ##__VA_ARGS__)   __MACRO(190, ##__VA_ARGS__)
#define VSF_MREPEAT192(__MACRO, ...)            VSF_MREPEAT191(__MACRO, ##__VA_ARGS__)   __MACRO(191, ##__VA_ARGS__)
#define VSF_MREPEAT193(__MACRO, ...)            VSF_MREPEAT192(__MACRO, ##__VA_ARGS__)   __MACRO(192, ##__VA_ARGS__)
#define VSF_MREPEAT194(__MACRO, ...)            VSF_MREPEAT193(__MACRO, ##__VA_ARGS__)   __MACRO(193, ##__VA_ARGS__)
#define VSF_MREPEAT195(__MACRO, ...)            VSF_MREPEAT194(__MACRO, ##__VA_ARGS__)   __MACRO(194, ##__VA_ARGS__)
#define VSF_MREPEAT196(__MACRO, ...)            VSF_MREPEAT195(__MACRO, ##__VA_ARGS__)   __MACRO(195, ##__VA_ARGS__)
#define VSF_MREPEAT197(__MACRO, ...)            VSF_MREPEAT196(__MACRO, ##__VA_ARGS__)   __MACRO(196, ##__VA_ARGS__)
#define VSF_MREPEAT198(__MACRO, ...)            VSF_MREPEAT197(__MACRO, ##__VA_ARGS__)   __MACRO(197, ##__VA_ARGS__)
#define VSF_MREPEAT199(__MACRO, ...)            VSF_MREPEAT198(__MACRO, ##__VA_ARGS__)   __MACRO(198, ##__VA_ARGS__)
#define VSF_MREPEAT200(__MACRO, ...)            VSF_MREPEAT199(__MACRO, ##__VA_ARGS__)   __MACRO(199, ##__VA_ARGS__)
#define VSF_MREPEAT201(__MACRO, ...)            VSF_MREPEAT200(__MACRO, ##__VA_ARGS__)   __MACRO(200, ##__VA_ARGS__)
#define VSF_MREPEAT202(__MACRO, ...)            VSF_MREPEAT201(__MACRO, ##__VA_ARGS__)   __MACRO(201, ##__VA_ARGS__)
#define VSF_MREPEAT203(__MACRO, ...)            VSF_MREPEAT202(__MACRO, ##__VA_ARGS__)   __MACRO(202, ##__VA_ARGS__)
#define VSF_MREPEAT204(__MACRO, ...)            VSF_MREPEAT203(__MACRO, ##__VA_ARGS__)   __MACRO(203, ##__VA_ARGS__)
#define VSF_MREPEAT205(__MACRO, ...)            VSF_MREPEAT204(__MACRO, ##__VA_ARGS__)   __MACRO(204, ##__VA_ARGS__)
#define VSF_MREPEAT206(__MACRO, ...)            VSF_MREPEAT205(__MACRO, ##__VA_ARGS__)   __MACRO(205, ##__VA_ARGS__)
#define VSF_MREPEAT207(__MACRO, ...)            VSF_MREPEAT206(__MACRO, ##__VA_ARGS__)   __MACRO(206, ##__VA_ARGS__)
#define VSF_MREPEAT208(__MACRO, ...)            VSF_MREPEAT207(__MACRO, ##__VA_ARGS__)   __MACRO(207, ##__VA_ARGS__)
#define VSF_MREPEAT209(__MACRO, ...)            VSF_MREPEAT208(__MACRO, ##__VA_ARGS__)   __MACRO(208, ##__VA_ARGS__)
#define VSF_MREPEAT210(__MACRO, ...)            VSF_MREPEAT209(__MACRO, ##__VA_ARGS__)   __MACRO(209, ##__VA_ARGS__)
#define VSF_MREPEAT211(__MACRO, ...)            VSF_MREPEAT210(__MACRO, ##__VA_ARGS__)   __MACRO(210, ##__VA_ARGS__)
#define VSF_MREPEAT212(__MACRO, ...)            VSF_MREPEAT211(__MACRO, ##__VA_ARGS__)   __MACRO(211, ##__VA_ARGS__)
#define VSF_MREPEAT213(__MACRO, ...)            VSF_MREPEAT212(__MACRO, ##__VA_ARGS__)   __MACRO(212, ##__VA_ARGS__)
#define VSF_MREPEAT214(__MACRO, ...)            VSF_MREPEAT213(__MACRO, ##__VA_ARGS__)   __MACRO(213, ##__VA_ARGS__)
#define VSF_MREPEAT215(__MACRO, ...)            VSF_MREPEAT214(__MACRO, ##__VA_ARGS__)   __MACRO(214, ##__VA_ARGS__)
#define VSF_MREPEAT216(__MACRO, ...)            VSF_MREPEAT215(__MACRO, ##__VA_ARGS__)   __MACRO(215, ##__VA_ARGS__)
#define VSF_MREPEAT217(__MACRO, ...)            VSF_MREPEAT216(__MACRO, ##__VA_ARGS__)   __MACRO(216, ##__VA_ARGS__)
#define VSF_MREPEAT218(__MACRO, ...)            VSF_MREPEAT217(__MACRO, ##__VA_ARGS__)   __MACRO(217, ##__VA_ARGS__)
#define VSF_MREPEAT219(__MACRO, ...)            VSF_MREPEAT218(__MACRO, ##__VA_ARGS__)   __MACRO(218, ##__VA_ARGS__)
#define VSF_MREPEAT220(__MACRO, ...)            VSF_MREPEAT219(__MACRO, ##__VA_ARGS__)   __MACRO(219, ##__VA_ARGS__)
#define VSF_MREPEAT221(__MACRO, ...)            VSF_MREPEAT220(__MACRO, ##__VA_ARGS__)   __MACRO(220, ##__VA_ARGS__)
#define VSF_MREPEAT222(__MACRO, ...)            VSF_MREPEAT221(__MACRO, ##__VA_ARGS__)   __MACRO(221, ##__VA_ARGS__)
#define VSF_MREPEAT223(__MACRO, ...)            VSF_MREPEAT222(__MACRO, ##__VA_ARGS__)   __MACRO(222, ##__VA_ARGS__)
#define VSF_MREPEAT224(__MACRO, ...)            VSF_MREPEAT223(__MACRO, ##__VA_ARGS__)   __MACRO(223, ##__VA_ARGS__)
#define VSF_MREPEAT225(__MACRO, ...)            VSF_MREPEAT224(__MACRO, ##__VA_ARGS__)   __MACRO(224, ##__VA_ARGS__)
#define VSF_MREPEAT226(__MACRO, ...)            VSF_MREPEAT225(__MACRO, ##__VA_ARGS__)   __MACRO(225, ##__VA_ARGS__)
#define VSF_MREPEAT227(__MACRO, ...)            VSF_MREPEAT226(__MACRO, ##__VA_ARGS__)   __MACRO(226, ##__VA_ARGS__)
#define VSF_MREPEAT228(__MACRO, ...)            VSF_MREPEAT227(__MACRO, ##__VA_ARGS__)   __MACRO(227, ##__VA_ARGS__)
#define VSF_MREPEAT229(__MACRO, ...)            VSF_MREPEAT228(__MACRO, ##__VA_ARGS__)   __MACRO(228, ##__VA_ARGS__)
#define VSF_MREPEAT230(__MACRO, ...)            VSF_MREPEAT229(__MACRO, ##__VA_ARGS__)   __MACRO(229, ##__VA_ARGS__)
#define VSF_MREPEAT231(__MACRO, ...)            VSF_MREPEAT230(__MACRO, ##__VA_ARGS__)   __MACRO(230, ##__VA_ARGS__)
#define VSF_MREPEAT232(__MACRO, ...)            VSF_MREPEAT231(__MACRO, ##__VA_ARGS__)   __MACRO(231, ##__VA_ARGS__)
#define VSF_MREPEAT233(__MACRO, ...)            VSF_MREPEAT232(__MACRO, ##__VA_ARGS__)   __MACRO(232, ##__VA_ARGS__)
#define VSF_MREPEAT234(__MACRO, ...)            VSF_MREPEAT233(__MACRO, ##__VA_ARGS__)   __MACRO(233, ##__VA_ARGS__)
#define VSF_MREPEAT235(__MACRO, ...)            VSF_MREPEAT234(__MACRO, ##__VA_ARGS__)   __MACRO(234, ##__VA_ARGS__)
#define VSF_MREPEAT236(__MACRO, ...)            VSF_MREPEAT235(__MACRO, ##__VA_ARGS__)   __MACRO(235, ##__VA_ARGS__)
#define VSF_MREPEAT237(__MACRO, ...)            VSF_MREPEAT236(__MACRO, ##__VA_ARGS__)   __MACRO(236, ##__VA_ARGS__)
#define VSF_MREPEAT238(__MACRO, ...)            VSF_MREPEAT237(__MACRO, ##__VA_ARGS__)   __MACRO(237, ##__VA_ARGS__)
#define VSF_MREPEAT239(__MACRO, ...)            VSF_MREPEAT238(__MACRO, ##__VA_ARGS__)   __MACRO(238, ##__VA_ARGS__)
#define VSF_MREPEAT240(__MACRO, ...)            VSF_MREPEAT239(__MACRO, ##__VA_ARGS__)   __MACRO(239, ##__VA_ARGS__)
#define VSF_MREPEAT241(__MACRO, ...)            VSF_MREPEAT240(__MACRO, ##__VA_ARGS__)   __MACRO(240, ##__VA_ARGS__)
#define VSF_MREPEAT242(__MACRO, ...)            VSF_MREPEAT241(__MACRO, ##__VA_ARGS__)   __MACRO(241, ##__VA_ARGS__)
#define VSF_MREPEAT243(__MACRO, ...)            VSF_MREPEAT242(__MACRO, ##__VA_ARGS__)   __MACRO(242, ##__VA_ARGS__)
#define VSF_MREPEAT244(__MACRO, ...)            VSF_MREPEAT243(__MACRO, ##__VA_ARGS__)   __MACRO(243, ##__VA_ARGS__)
#define VSF_MREPEAT245(__MACRO, ...)            VSF_MREPEAT244(__MACRO, ##__VA_ARGS__)   __MACRO(244, ##__VA_ARGS__)
#define VSF_MREPEAT246(__MACRO, ...)            VSF_MREPEAT245(__MACRO, ##__VA_ARGS__)   __MACRO(245, ##__VA_ARGS__)
#define VSF_MREPEAT247(__MACRO, ...)            VSF_MREPEAT246(__MACRO, ##__VA_ARGS__)   __MACRO(246, ##__VA_ARGS__)
#define VSF_MREPEAT248(__MACRO, ...)            VSF_MREPEAT247(__MACRO, ##__VA_ARGS__)   __MACRO(247, ##__VA_ARGS__)
#define VSF_MREPEAT249(__MACRO, ...)            VSF_MREPEAT248(__MACRO, ##__VA_ARGS__)   __MACRO(248, ##__VA_ARGS__)
#define VSF_MREPEAT250(__MACRO, ...)            VSF_MREPEAT249(__MACRO, ##__VA_ARGS__)   __MACRO(249, ##__VA_ARGS__)
#define VSF_MREPEAT251(__MACRO, ...)            VSF_MREPEAT250(__MACRO, ##__VA_ARGS__)   __MACRO(250, ##__VA_ARGS__)
#define VSF_MREPEAT252(__MACRO, ...)            VSF_MREPEAT251(__MACRO, ##__VA_ARGS__)   __MACRO(251, ##__VA_ARGS__)
#define VSF_MREPEAT253(__MACRO, ...)            VSF_MREPEAT252(__MACRO, ##__VA_ARGS__)   __MACRO(252, ##__VA_ARGS__)
#define VSF_MREPEAT254(__MACRO, ...)            VSF_MREPEAT253(__MACRO, ##__VA_ARGS__)   __MACRO(253, ##__VA_ARGS__)
#define VSF_MREPEAT255(__MACRO, ...)            VSF_MREPEAT254(__MACRO, ##__VA_ARGS__)   __MACRO(254, ##__VA_ARGS__)
#define VSF_MREPEAT256(__MACRO, ...)            VSF_MREPEAT255(__MACRO, ##__VA_ARGS__)   __MACRO(255, ##__VA_ARGS__)

#endif

#ifdef __cplusplus
}
#endif

#endif  // _VSF_MREPEAT_H_
