def __init__(self): ...
environ: dict
O_RDONLY: int
O_WRONLY: int
O_RDWR: int
O_APPEND: int
O_CREAT: int
def listdir(self, *path: str) -> list: ...
def getcwd(self) -> str: ...
def mkdir(self, *arg): ...
def makedirs(self, path: str, *mode: int): ...
def rmdir(self, path: str): ...
def chdir(self, path: str): ...
def rename(self, old: str, new: str): ...
def remove(self, path: str): ...
def open(self, *arg) -> any: ...
def read(self, *arg): -> str: ...
def write(self, *arg): -> int: ...
def ioctl(self, *arg): -> int: ...

class path:
	def join(self, *path: str) -> str: ...
	def split(self, path: str) -> tuple: ...
	def splitext(self, path: str) -> tuple: ...
	def basename(self, path: str) -> str: ...
	def dirname(self, path: str) -> str: ...
	def exists(self, path: str) -> bool: ...
	def isdir(self, path: str) -> bool: ...
	def isfile(self, path: str) -> bool: ...
	def isabs(self, path: str) -> bool: ...
	def abspath(self, path: str) -> str: ...
