if(VSF_USE_LVGL)
    include(${VSF_CMAKE_ROOT}/3rd-party/lvgl.cmake)
    if(VSF_LVGL_USE_FREETYPE)
        set(VSF_USE_FREETYPE 1)
    endif()
endif()

if(VSF_USE_FREETYPE)
    include(${VSF_CMAKE_ROOT}/3rd-party/freetype.cmake)
endif()
