set(VSF_HAL_CHIP_VENDOR     generic)
set(VSF_ARCH_SERIES         generic)

set(VSF_HOST_SYSTEM         linux)
set(VSF_HOST_SYSTEM32       1)
set(VSF_HOST_HAS_LIBUSB     1)

if(NOT DEFINED MAX_CONSTRUCTOR_PRIORITY)
    set(MAX_CONSTRUCTOR_PRIORITY 65535)
endif()

set(VSF_TARGET_DEFINITIONS
    "__LINUX__"
    "__CPU_GENERIC__"
    "MAX_CONSTRUCTOR_PRIORITY=${MAX_CONSTRUCTOR_PRIORITY}"
)