set(VSF_HAL_CHIP_VENDOR     x86)
set(VSF_ARCH_SERIES         x86)

set(VSF_HOST_SYSTEM         linux)
set(VSF_HOST_SYSTEM64       1)
set(VSF_HOST_HAS_LIBUSB     1)

if(NOT DEFINED MAX_CONSTRUCTOR_PRIORITY)
    set(MAX_CONSTRUCTOR_PRIORITY 65535)
endif()

set(VSF_TARGET_DEFINITIONS
    "__LINUX__"
    "__CPU_X64__"
    "__VSF64__"
    "MAX_CONSTRUCTOR_PRIORITY=${MAX_CONSTRUCTOR_PRIORITY}"
)
