/*****************************************************************************
 *   Copyright(C)2009-2022 by VSF Team                                       *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 ****************************************************************************/

#ifndef __VSF_SDL2_KEYCODE_H__
#define __VSF_SDL2_KEYCODE_H__

/*============================ INCLUDES ======================================*/

#ifdef __cplusplus
extern "C" {
#endif

/*============================ MACROS ========================================*/
/*============================ MACROFIED FUNCTIONS ===========================*/
/*============================ TYPES =========================================*/

typedef int32_t SDL_Keycode;
enum {
    SDLK_UNKNOWN                = 0,

    SDLK_BACKSPACE              = '\b',
    SDLK_RETURN                 = '\r',
    SDLK_ESCAPE                 = '\033',
    SDLK_TAB                    = '\t',
    SDLK_SPACE                  = ' ',
    SDLK_EXCLAIM                = '!',
    SDLK_QUOTEDBL               = '"',
    SDLK_HASH                   = '#',
    SDLK_PERCENT                = '%',
    SDLK_DOLLAR                 = '$',
    SDLK_AMPERSAND              = '&',
    SDLK_QUOTE                  = '\'',
    SDLK_LEFTPAREN              = '(',
    SDLK_RIGHTPAREN             = ')',
    SDLK_ASTERISK               = '*',
    SDLK_PLUS                   = '+',
    SDLK_COMMA                  = ',',
    SDLK_MINUS                  = '-',
    SDLK_PERIOD                 = '.',
    SDLK_SLASH                  = '/',

    SDLK_0                      = '0',
    SDLK_1                      = '1',
    SDLK_2                      = '2',
    SDLK_3                      = '3',
    SDLK_4                      = '4',
    SDLK_5                      = '5',
    SDLK_6                      = '6',
    SDLK_7                      = '7',
    SDLK_8                      = '8',
    SDLK_9                      = '9',

    SDLK_COLON                  = ':',
    SDLK_SEMICOLON              = ';',
    SDLK_LESS                   = '<',
    SDLK_EQUALS                 = '=',
    SDLK_GREATER                = '>',
    SDLK_QUESTION               = '?',
    SDLK_AT                     = '@',
    SDLK_LEFTBRACKET            = '[',
    SDLK_BACKSLASH              = '\\',
    SDLK_RIGHTBRACKET           = ']',
    SDLK_CARET                  = '^',
    SDLK_UNDERSCORE             = '_',
    SDLK_BACKQUOTE              = '`',
    SDLK_LEFTBRACE              = '{',
    SDLK_RIGHTBRACE             = '}',

    SDLK_a                      = 'a',
    SDLK_b                      = 'b',
    SDLK_c                      = 'c',
    SDLK_d                      = 'd',
    SDLK_e                      = 'e',
    SDLK_f                      = 'f',
    SDLK_g                      = 'g',
    SDLK_h                      = 'h',
    SDLK_i                      = 'i',
    SDLK_j                      = 'j',
    SDLK_k                      = 'k',
    SDLK_l                      = 'l',
    SDLK_m                      = 'm',
    SDLK_n                      = 'n',
    SDLK_o                      = 'o',
    SDLK_p                      = 'p',
    SDLK_q                      = 'q',
    SDLK_r                      = 'r',
    SDLK_s                      = 's',
    SDLK_t                      = 't',
    SDLK_u                      = 'u',
    SDLK_v                      = 'v',
    SDLK_w                      = 'w',
    SDLK_x                      = 'x',
    SDLK_y                      = 'y',
    SDLK_z                      = 'z',

    // 256 - 287
    SDLK_KP_0                   = 256,
    SDLK_KP_1                   = 257,
    SDLK_KP_2                   = 258,
    SDLK_KP_3                   = 259,
    SDLK_KP_4                   = 260,
    SDLK_KP_5                   = 261,
    SDLK_KP_6                   = 262,
    SDLK_KP_7                   = 263,
    SDLK_KP_8                   = 264,
    SDLK_KP_9                   = 265,
    SDLK_KP0                    = SDLK_KP_0,
    SDLK_KP1                    = SDLK_KP_1,
    SDLK_KP2                    = SDLK_KP_2,
    SDLK_KP3                    = SDLK_KP_3,
    SDLK_KP4                    = SDLK_KP_4,
    SDLK_KP5                    = SDLK_KP_5,
    SDLK_KP6                    = SDLK_KP_6,
    SDLK_KP7                    = SDLK_KP_7,
    SDLK_KP8                    = SDLK_KP_8,
    SDLK_KP9                    = SDLK_KP_9,
    SDLK_KP_PERIOD              = 266,
    SDLK_KP_DIVIDE              = 267,
    SDLK_KP_MULTIPLY            = 268,
    SDLK_KP_MINUS               = 269,
    SDLK_KP_PLUS                = 270,
    SDLK_KP_ENTER               = 271,
    SDLK_KP_EQUALS              = 272,
    SDLK_NUMLOCKCLEAR           = 275,

    // 288 - 310
    SDLK_UP                     = 288,
    SDLK_DOWN                   = 289,
    SDLK_RIGHT                  = 290,
    SDLK_LEFT                   = 291,
    SDLK_INSERT                 = 292,
    SDLK_HOME                   = 293,
    SDLK_END                    = 294,
    SDLK_PAGEUP                 = 295,
    SDLK_PAGEDOWN               = 296,
    SDLK_DELETE                 = 297,
    SDLK_PAUSE                  = 298,

    // 320 - 351
    SDLK_F1                     = 320,
    SDLK_F2                     = 321,
    SDLK_F3                     = 322,
    SDLK_F4                     = 323,
    SDLK_F5                     = 324,
    SDLK_F6                     = 325,
    SDLK_F7                     = 326,
    SDLK_F8                     = 327,
    SDLK_F9                     = 328,
    SDLK_F10                    = 329,
    SDLK_F11                    = 330,
    SDLK_F12                    = 331,
    SDLK_F13                    = 332,
    SDLK_F14                    = 333,
    SDLK_F15                    = 334,
    SDLK_F16                    = 335,
    SDLK_F17                    = 336,
    SDLK_F18                    = 337,
    SDLK_F19                    = 338,
    SDLK_F20                    = 339,
    SDLK_F21                    = 340,
    SDLK_F22                    = 341,
    SDLK_F23                    = 342,
    SDLK_F24                    = 343,
    SDLK_CAPSLOCK               = 344,

    // 352 - 383
    SDLK_LCTRL                  = 352,
    SDLK_LSHIFT                 = 353,
    SDLK_LALT                   = 354,
    SDLK_LGUI                   = 355,
    SDLK_RCTRL                  = 356,
    SDLK_RSHIFT                 = 357,
    SDLK_RALT                   = 358,
    SDLK_RGUI                   = 359,
};

typedef enum SDL_Keymod {
    KMOD_NONE                   = 0,
    KMOD_LSHIFT                 = 1 << 0,
    KMOD_RSHIFT                 = 1 << 1,
    KMOD_LCTRL                  = 1 << 2,
    KMOD_RCTRL                  = 1 << 3,
    KMOD_LALT                   = 1 << 4,
    KMOD_RALT                   = 1 << 5,
    KMOD_LGUI                   = 1 << 6,
    KMOD_RGUI                   = 1 << 7,
    KMOD_LMETA                  = 1 << 8,
    KMOD_RMETA                  = 1 << 9,
    KMOD_NUM                    = 1 << 12,
    KMOD_CAPS                   = 1 << 13,
    KMOD_MODE                   = 1 << 14,

    KMOD_CTRL                   = (KMOD_LCTRL | KMOD_RCTRL),
    KMOD_SHIFT                  = (KMOD_LSHIFT | KMOD_RSHIFT),
    KMOD_ALT                    = (KMOD_LALT | KMOD_RALT),
    KMOD_GUI                    = (KMOD_LGUI | KMOD_RGUI),
    KMOD_META                   = (KMOD_LMETA | KMOD_RMETA),

    KMOD_RESERVED               = 0x8000,
} SDL_Keymod;

// TODO:
typedef enum {
    SDL_SCANCODE_UNKNOWN        = 0,

    SDL_SCANCODE_A              = 4,
    SDL_SCANCODE_B              = 5,
    SDL_SCANCODE_C              = 6,
    SDL_SCANCODE_D              = 7,
    SDL_SCANCODE_E              = 8,
    SDL_SCANCODE_F              = 9,
    SDL_SCANCODE_G              = 10,
    SDL_SCANCODE_H              = 11,
    SDL_SCANCODE_I              = 12,
    SDL_SCANCODE_J              = 13,
    SDL_SCANCODE_K              = 14,
    SDL_SCANCODE_L              = 15,
    SDL_SCANCODE_M              = 16,
    SDL_SCANCODE_N              = 17,
    SDL_SCANCODE_O              = 18,
    SDL_SCANCODE_P              = 19,
    SDL_SCANCODE_Q              = 20,
    SDL_SCANCODE_R              = 21,
    SDL_SCANCODE_S              = 22,
    SDL_SCANCODE_T              = 23,
    SDL_SCANCODE_U              = 24,
    SDL_SCANCODE_V              = 25,
    SDL_SCANCODE_W              = 26,
    SDL_SCANCODE_X              = 27,
    SDL_SCANCODE_Y              = 28,
    SDL_SCANCODE_Z              = 29,

    SDL_SCANCODE_1              = 30,
    SDL_SCANCODE_2              = 31,
    SDL_SCANCODE_3              = 32,
    SDL_SCANCODE_4              = 33,
    SDL_SCANCODE_5              = 34,
    SDL_SCANCODE_6              = 35,
    SDL_SCANCODE_7              = 36,
    SDL_SCANCODE_8              = 37,
    SDL_SCANCODE_9              = 38,
    SDL_SCANCODE_0              = 39,

    SDL_SCANCODE_RETURN         = 40,
    SDL_SCANCODE_ESCAPE         = 41,
    SDL_SCANCODE_BACKSPACE      = 42,
    SDL_SCANCODE_TAB            = 43,
    SDL_SCANCODE_SPACE          = 44,

    SDL_SCANCODE_MINUS          = 45,
    SDL_SCANCODE_EQUALS         = 46,
    SDL_SCANCODE_LEFTBRACKET    = 47,
    SDL_SCANCODE_RIGHTBRACKET   = 48,
    SDL_SCANCODE_BACKSLASH      = 49,
    SDL_SCANCODE_NONUSHASH      = 50,
    SDL_SCANCODE_SEMICOLON      = 51,
    SDL_SCANCODE_APOSTROPHE     = 52,
    SDL_SCANCODE_GRAVE          = 53,
    SDL_SCANCODE_COMMA          = 54,
    SDL_SCANCODE_PERIOD         = 55,
    SDL_SCANCODE_SLASH          = 56,
    SDL_SCANCODE_CAPSLOCK       = 57,

    SDL_SCANCODE_F1             = 58,
    SDL_SCANCODE_F2             = 59,
    SDL_SCANCODE_F3             = 60,
    SDL_SCANCODE_F4             = 61,
    SDL_SCANCODE_F5             = 62,
    SDL_SCANCODE_F6             = 63,
    SDL_SCANCODE_F7             = 64,
    SDL_SCANCODE_F8             = 65,
    SDL_SCANCODE_F9             = 66,
    SDL_SCANCODE_F10            = 67,
    SDL_SCANCODE_F11            = 68,
    SDL_SCANCODE_F12            = 69,

    SDL_SCANCODE_PRINTSCREEN    = 70,
    SDL_SCANCODE_SCROLLLOCK     = 71,
    SDL_SCANCODE_PAUSE          = 72,
    SDL_SCANCODE_INSERT         = 73,
    SDL_SCANCODE_HOME           = 74,
    SDL_SCANCODE_PAGEUP         = 75,
    SDL_SCANCODE_DELETE         = 76,
    SDL_SCANCODE_END            = 77,
    SDL_SCANCODE_PAGEDOWN       = 78,
    SDL_SCANCODE_RIGHT          = 79,
    SDL_SCANCODE_LEFT           = 80,
    SDL_SCANCODE_DOWN           = 81,
    SDL_SCANCODE_UP             = 82,
    SDL_SCANCODE_NUMLOCKCLEAR   = 83,

    SDL_SCANCODE_KP_DIVIDE      = 84,
    SDL_SCANCODE_KP_MULTIPLY    = 85,
    SDL_SCANCODE_KP_MINUS       = 86,
    SDL_SCANCODE_KP_PLUS        = 87,
    SDL_SCANCODE_KP_ENTER       = 88,
    SDL_SCANCODE_KP_1           = 89,
    SDL_SCANCODE_KP_2           = 90,
    SDL_SCANCODE_KP_3           = 91,
    SDL_SCANCODE_KP_4           = 92,
    SDL_SCANCODE_KP_5           = 93,
    SDL_SCANCODE_KP_6           = 94,
    SDL_SCANCODE_KP_7           = 95,
    SDL_SCANCODE_KP_8           = 96,
    SDL_SCANCODE_KP_9           = 97,
    SDL_SCANCODE_KP_0           = 98,
    SDL_SCANCODE_KP_PERIOD      = 99,
    SDL_SCANCODE_NONUSBACKSLASH = 100,
    SDL_SCANCODE_APPLICATION    = 101,
    SDL_SCANCODE_POWER          = 102,
    SDL_SCANCODE_KP_EQUALS      = 103,

    SDL_SCANCODE_F13            = 104,
    SDL_SCANCODE_F14            = 105,
    SDL_SCANCODE_F15            = 106,
    SDL_SCANCODE_F16            = 107,
    SDL_SCANCODE_F17            = 108,
    SDL_SCANCODE_F18            = 109,
    SDL_SCANCODE_F19            = 110,
    SDL_SCANCODE_F20            = 111,
    SDL_SCANCODE_F21            = 112,
    SDL_SCANCODE_F22            = 113,
    SDL_SCANCODE_F23            = 114,
    SDL_SCANCODE_F24            = 115,

    SDL_SCANCODE_EXECUTE        = 116,
    SDL_SCANCODE_HELP           = 117,
    SDL_SCANCODE_MENU           = 118,
    SDL_SCANCODE_SELECT         = 119,
    SDL_SCANCODE_STOP           = 120,
    SDL_SCANCODE_AGAIN          = 121,
    SDL_SCANCODE_UNDO           = 122,
    SDL_SCANCODE_CUT            = 123,
    SDL_SCANCODE_COPY           = 124,
    SDL_SCANCODE_PASTE          = 125,
    SDL_SCANCODE_FIND           = 126,
    SDL_SCANCODE_MUTE           = 127,
    SDL_SCANCODE_VOLUMEUP       = 128,
    SDL_SCANCODE_VOLUMEDOWN     = 129,

    SDL_SCANCODE_CANCEL         = 155,
    SDL_SCANCODE_CLEAR          = 156,

    SDL_SCANCODE_LCTRL          = 224,
    SDL_SCANCODE_LSHIFT         = 225,
    SDL_SCANCODE_LALT           = 226,
    SDL_SCANCODE_LGUI           = 227,
    SDL_SCANCODE_RCTRL          = 228,
    SDL_SCANCODE_RSHIFT         = 229,
    SDL_SCANCODE_RALT           = 230,
    SDL_SCANCODE_RGUI           = 231,

    SDL_SCANCODE_AUDIONEXT      = 258,
    SDL_SCANCODE_AUDIOPREV      = 259,
    SDL_SCANCODE_AUDIOSTOP      = 260,
    SDL_SCANCODE_AUDIOPLAY      = 261,
    SDL_SCANCODE_AUDIOMUTE      = 262,
    SDL_SCANCODE_MEDIASELECT    = 263,
    SDL_SCANCODE_WWW            = 264,
    SDL_SCANCODE_MAIL           = 265,
    SDL_SCANCODE_CALCULATOR     = 266,
    SDL_SCANCODE_COMPUTER       = 267,
    SDL_SCANCODE_AC_SEARCH      = 268,
    SDL_SCANCODE_AC_HOME        = 269,
    SDL_SCANCODE_AC_BACK        = 270,
    SDL_SCANCODE_AC_FORWARD     = 271,
    SDL_SCANCODE_AC_STOP        = 272,
    SDL_SCANCODE_AC_REFRESH     = 273,
    SDL_SCANCODE_AC_BOOKMARKS   = 274,

    SDL_NUM_SCANCODES           = 512,
} SDL_Scancode;

#ifdef __cplusplus
}
#endif

#endif      // __VSF_SDL2_KEYCODE_H__
