/*****************************************************************************
 *   Copyright(C)2009-2022 by VSF Team                                       *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 ****************************************************************************/

/*
 * RT2870 firmware blob — weak placeholder.
 * =========================================
 *
 * The actual rt2870.bin (8 KiB) MUST be placed into __rt2870_firmware_data[]
 * with a matching __rt2870_firmware_size before the driver can do anything
 * useful with real hardware.
 *
 * The symbols are declared `weak` so that this file ships as a 0-byte stub
 * by default; an integrator overrides them by providing a strong definition
 * in their own translation unit (typically generated by `xxd -i rt2870.bin`
 * + a tiny shim that renames the array).  Example shim:
 *
 *     // user_rt2870_firmware.c
 *     const uint8_t  __rt2870_firmware_data[] = { 0x01, 0x23, ... };
 *     const uint32_t __rt2870_firmware_size   = sizeof(__rt2870_firmware_data);
 *
 * The chip driver checks `__rt2870_firmware_size != 0` at probe time:
 *   - size == 0  => skip firmware upload
 *   - size  > 0  => upload via vsf_wifi_run_blob, then issue post-fw
 *                   handshake script defined in vsf_wifi_rt28xx.c.
 *
 * Loading protocol (per rt2x00 / rt2870 USB datasheet excerpt):
 *
 *   - Vendor request 0x01 (multi-register write), wValue = 0x3000 + offset,
 *     wIndex = 0, wLength = chunk_size, data = blob[offset : offset+chunk]
 *     Chunks are 64 bytes by default (configurable via the bus driver).
 *
 *   - After the entire blob is shipped, the post-fw script clears the H2M
 *     mailbox + releases PBF_SYS_CTRL bit 7, instructing the MCU to leave
 *     patch-RAM mode and start executing firmware.
 *
 * Hardware bring-up checklist (see also BRINGUP.md):
 *   [ ] Replace this stub with real rt2870.bin
 *   [ ] Validate fw_size == 8192 (RT2870 / RT3070) on startup
 *   [ ] Verify USB_DEVICE_MODE switch and MCU_READY poll
 *==========================================================================*/

#include "../../vsf_wifi.h"

#if VSF_USE_WIFI == ENABLED && VSF_WIFI_USE_RT28XX == ENABLED

#include "utilities/compiler/compiler.h"
#include <stdint.h>

VSF_CAL_WEAK(__rt2870_firmware_data)
const uint8_t  __rt2870_firmware_data[1] = { 0 };

VSF_CAL_WEAK(__rt2870_firmware_size)
const uint32_t __rt2870_firmware_size   = 0;

#endif      // VSF_USE_WIFI && VSF_WIFI_USE_RT28XX
