name: vsf cmake native build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  cmake-native-build:
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest] # [ubuntu-latest, macos-12]
        src: [linux]        #[linux, macos]
        exclude:
          - os: ubuntu-latest
            src: macos
          - os: macos-12
            src: linux

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true # without recursive

    - name: install depends
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential clang ninja-build libsdl2-dev libbsd-dev libusb-dev libusb-1.0 python3 python3-pip
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install gcc llvm sdl2 libusb ninja

            echo "" >> ~/.bash_profile # fixed last line without line break
            echo "export LIBRARY_PATH=/usr/local/lib" >> ~/.bash_profile
            echo "export C_INCLUDE_PATH=/usr/local/include" >> ~/.bash_profile

          fi
          pip3 install pytest pytest-bdd pexpect simple-hexdump
      shell: bash

    - name: configure cmake
      run: cmake -GNinja -S ${SOURCE_PATH} -B ${SOURCE_PATH}/build
      shell: bash -ileo pipefail {0}
      env:
        CC: ${{matrix.cc}}
        VSF_PATH: ${{github.workspace}}
        SOURCE_PATH: ${{github.workspace}}/example/template/project/cmake/${{matrix.src}}

    - name: build
      run: cmake --build ${SOURCE_PATH}/build -v
      shell: bash -ileo pipefail {0}
      env:
        SOURCE_PATH: ${{github.workspace}}/example/template/project/cmake/${{matrix.src}}

    #- name: test
    #  run: pytest -m "base or memory or linux-only" --verbose -o log_cli=true --log-cli-level="DEBUG" --vsf_template=${{github.workspace}}/example/template/project/cmake/${{matrix.src}}/build/vsf_template
    #  working-directory: ${{github.workspace}}/test/pytest
